// @vitest-environment jsdom
/**
 * Tests for `<CollectionComposer>`: the access gate (nothing for visitors,
 * `unauthorized` override, dev warn on non-creatable collections), the
 * schema-driven form render, required validation, and the create POST → reset
 * + confirmation flow. Mounted through the real CmsProvider/CollectionProvider
 * stack with a mocked fetch, same pattern as the provider auth tests.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, fireEvent, waitFor } from "@testing-library/react";

// The drawer is heavyweight and lazy; the composer never needs it.
vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/yeni-haber",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../components/CmsProvider.jsx";
import { CollectionComposer } from "../components/CollectionComposer.jsx";

const BASE = "https://api.test";

const jsonRes = (body, status = 200) =>
  new Response(JSON.stringify(body), { status });

const newsMeta = (overrides = {}) => ({
  collectionKey: "news",
  canCreate: true,
  slugSource: "AutoGenerated",
  schema: {
    fields: [
      { name: "title", label: "Başlık", type: "ShortText", required: true, readOnly: false, options: null, fields: null, help: null },
      { name: "body", label: "İçerik", type: "LongText", required: false, readOnly: false, options: null, fields: null, help: null },
    ],
  },
  ...overrides,
});

/** Requests captured as [method, url] for order-insensitive assertions. */
let requests;

function mockFetch({ me }) {
  requests = [];
  global.fetch = vi.fn(async (input, init) => {
    const url = String(input);
    const method = init?.method ?? "GET";
    requests.push([method, url]);
    // The /me endpoint returns a bare array (see CollectionProvider: the
    // response is used directly as `myCollections`).
    if (url.includes("/cms/collections/me")) return jsonRes(me);
    if (url.includes("/cms/collections/news") && method === "POST") {
      const sent = JSON.parse(String(init.body));
      return jsonRes({
        id: "row-1",
        collectionKey: "news",
        slug: "yeni-haber",
        data: sent.data,
        version: 1,
        canEdit: true,
      });
    }
    if (url.includes("/cms/collections/news")) {
      return jsonRes({ items: [], total: 0, offset: 0, limit: 50 });
    }
    return jsonRes({ slug: "/", blocks: [] });
  });
}

function renderComposer({ isAdmin = true, props = {} } = {}) {
  return render(
    <CmsProvider config={{ baseUrl: BASE }} isAdmin={isAdmin} getAccessToken={async () => "tok"}>
      <CollectionComposer collection="news" {...props} />
    </CmsProvider>,
  );
}

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("access gate", () => {
  it("renders nothing for public visitors", async () => {
    mockFetch({ me: [] });
    renderComposer({ isAdmin: false });
    await waitFor(() => expect(screen.queryByText("Başlık")).toBeNull());
    expect(document.querySelector(".inscribed-composer")).toBeNull();
  });

  it("renders the unauthorized node for sessions without access to the collection", async () => {
    mockFetch({ me: [] });
    renderComposer({ props: { unauthorized: <p>Erişim yok</p> } });
    await waitFor(() => expect(screen.getByText("Erişim yok")).toBeTruthy());
  });

  it("warns in dev when an admin's key isn't in the accessible list (the silent-blank trap)", async () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    // News exists under a different key than the one the host passed.
    mockFetch({ me: [newsMeta({ collectionKey: "haberler" })] });
    renderComposer(); // asks for "news"
    await waitFor(() =>
      expect(warn.mock.calls.some(([msg]) => String(msg).includes("accessible collections"))).toBe(true),
    );
    expect(document.querySelector(".inscribed-composer")).toBeNull();
  });

  it("renders nothing (with a dev warn) when the collection isn't creatable", async () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    mockFetch({ me: [newsMeta({ canCreate: false })] });
    renderComposer();
    await waitFor(() =>
      expect(warn.mock.calls.some(([msg]) => String(msg).includes("isn't creatable"))).toBe(true),
    );
    expect(document.querySelector(".inscribed-composer")).toBeNull();
  });
});

describe("create flow", () => {
  beforeEach(() => {
    mockFetch({ me: [newsMeta()] });
  });

  it("renders the schema form once /me arrives", async () => {
    renderComposer();
    await waitFor(() => expect(screen.getByText("Başlık")).toBeTruthy());
    expect(screen.getByText("İçerik")).toBeTruthy();
    expect(screen.getByText("Oluştur")).toBeTruthy();
  });

  it("blocks submit while a required field is empty", async () => {
    renderComposer();
    await waitFor(() => expect(screen.getByText("Oluştur")).toBeTruthy());
    fireEvent.click(screen.getByText("Oluştur"));
    expect(await screen.findByText(/Zorunlu alan eksik: Başlık/)).toBeTruthy();
    expect(requests.some(([m]) => m === "POST")).toBe(false);
  });

  it("POSTs the payload, resets the form, and confirms inline", async () => {
    renderComposer({ props: { submitLabel: "Haberi yayınla" } });
    await waitFor(() => expect(screen.getByText("Haberi yayınla")).toBeTruthy());

    const [titleInput] = Array.from(document.querySelectorAll("input.inscribed-field"));
    fireEvent.change(titleInput, { target: { value: "Merhaba" } });
    fireEvent.click(screen.getByText("Haberi yayınla"));

    expect(await screen.findByText("Kaydedildi.")).toBeTruthy();
    const post = global.fetch.mock.calls.find(([, init]) => init?.method === "POST");
    expect(post).toBeTruthy();
    expect(JSON.parse(String(post[1].body)).data.title).toBe("Merhaba");
    expect(/** @type {HTMLInputElement} */ (titleInput).value).toBe("");
  });

  it("hands the created item to onCreated instead of confirming inline", async () => {
    const onCreated = vi.fn();
    renderComposer({ props: { onCreated } });
    await waitFor(() => expect(screen.getByText("Oluştur")).toBeTruthy());

    const [titleInput] = Array.from(document.querySelectorAll("input.inscribed-field"));
    fireEvent.change(titleInput, { target: { value: "Merhaba" } });
    fireEvent.click(screen.getByText("Oluştur"));

    await waitFor(() => expect(onCreated).toHaveBeenCalledTimes(1));
    expect(onCreated.mock.calls[0][0].slug).toBe("yeni-haber");
    expect(screen.queryByText("Kaydedildi.")).toBeNull();
  });
});
