// @vitest-environment jsdom
/**
 * What a remounted provider starts from for an editor. A language switch
 * remounts `CmsProvider` and its collection layer; without the carry the new
 * one shows the published site and an empty `/me` until its own reads answer.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, cleanup, act, screen, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/",
  useRouter: () => ({ refresh: () => {}, push: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { useCmsContext } from "../../shared/state/cms-context.js";
import { useCollectionContext } from "../../collections/context.js";
import { useStoreSelector } from "../../shared/state/store.js";
import { routeKey } from "../../shared/route.js";

const CONFIG = { baseUrl: "https://api.test" };
const block = (draftValue) => ({
  blockPath: "hero.title", blockType: "ShortText", value: "Yayında", draftValue, version: 1, sortOrder: 1,
});
const PUBLISHED = { pages: [{ slug: "/", blocks: [block(null)] }], global: [] };
const WITH_DRAFT = { pages: [{ slug: "/", blocks: [block("Taslak")] }], global: [] };
const NEWS = [{ collectionKey: "news", canCreate: false, slugSource: "AutoGenerated", schema: { fields: [] } }];
const never = () => new Promise(() => {});

const probe = /** @type {{ ctx?: * }} */ ({});

function Probe() {
  const ctx = useCmsContext();
  probe.ctx = ctx;
  const hero = useStoreSelector(ctx.blocksStore, (s) => s.get(routeKey("/", null))?.get("hero.title"));
  const draft = useStoreSelector(ctx.contentDraftsStore, (m) => m.get("hero.title"));
  const meta = useStoreSelector(useCollectionContext().collectionStore, (s) => s.meta);
  return (
    <>
      <p data-testid="hero">{draft ?? hero?.draftValue ?? hero?.value}</p>
      <p data-testid="mine">{meta.isLoading ? "loading" : meta.order.map((c) => c.collectionKey).join(",")}</p>
    </>
  );
}

/** @param {{ user: string, site?: () => Promise<*>, mine?: () => Promise<*>, onSignOut?: () => void, providerKey?: string }} opts */
const provider = ({ user, site = never, mine = never, onSignOut, providerKey }) => (
  <CmsProvider
    key={providerKey}
    collections={CollectionProvider}
    config={CONFIG}
    transport={/** @type {*} */ ({
      getSiteContent: vi.fn(site),
      getMyCollections: vi.fn(mine),
      updateDraft: vi.fn(async () => undefined),
    })}
    isAdmin
    userSub={user}
    getAccessToken={async () => "tok"}
    onSignOut={onSignOut}
    initialSite={PUBLISHED}
  >
    <Probe />
  </CmsProvider>
);

/** @param {Parameters<typeof provider>[0]} opts */
async function mount(opts) {
  let view;
  await act(async () => {
    view = render(provider(opts));
  });
  return /** @type {ReturnType<typeof render>} */ (view);
}

const hero = () => screen.getByTestId("hero").textContent;
const mine = () => screen.getByTestId("mine").textContent;

afterEach(() => {
  cleanup();
});

describe("a provider remounted for the same editor", () => {
  it("shows the drafts the last one had, before its own read answers", async () => {
    const first = await mount({ user: "u1", site: async () => WITH_DRAFT });
    await waitFor(() => expect(hero()).toBe("Taslak"));
    first.unmount();

    await mount({ user: "u1" });
    expect(hero()).toBe("Taslak");
  });

  it("follows a provider that replaces it in one render, as a language switch does", async () => {
    // The new provider renders before the old one unmounts, so it cannot wait
    // for anything the old one would do on its way out.
    const view = await mount({ user: "u7", site: async () => WITH_DRAFT, providerKey: "tr" });
    await waitFor(() => expect(hero()).toBe("Taslak"));

    await act(async () => {
      view.rerender(provider({ user: "u7", providerKey: "en" }));
    });
    expect(hero()).toBe("Taslak");
  });

  it("keeps a draft typed just before the remount", async () => {
    const first = await mount({ user: "u2", site: async () => PUBLISHED });
    await act(async () => {});
    act(() => probe.ctx.setDraft("hero.title", "Yazılan"));
    first.unmount();

    await mount({ user: "u2" });
    expect(hero()).toBe("Yazılan");
  });

  it("starts another editor from the published site", async () => {
    const first = await mount({ user: "u3", site: async () => WITH_DRAFT });
    await waitFor(() => expect(hero()).toBe("Taslak"));
    first.unmount();

    await mount({ user: "u4" });
    expect(hero()).toBe("Yayında");
  });

  it("forgets it all on sign-out", async () => {
    const first = await mount({ user: "u5", site: async () => WITH_DRAFT, onSignOut: () => {} });
    await waitFor(() => expect(hero()).toBe("Taslak"));
    act(() => probe.ctx.onSignOut());
    first.unmount();

    await mount({ user: "u5" });
    expect(hero()).toBe("Yayında");
  });

  it("lists the collections the last /me answered while the new one is out", async () => {
    const first = await mount({ user: "u6", mine: async () => NEWS });
    await waitFor(() => expect(mine()).toBe("news"));
    first.unmount();

    await mount({ user: "u6" });
    expect(mine()).toBe("news");
  });
});
