"use client";

/**
 * @file The create lane: `CreateButton`, the pinned "+ Yeni" row inside the
 * parallax list layer, and `CreatePane`, the create-mode detail pane it opens.
 *
 * The two render in different slots of the panel and talk through the shared
 * list cache: the pending virtual row's `draftData` is what puts the draft
 * badge on the button.
 */

import { useId, useState } from "react";
import { Plus } from "../../shared/style/icons.jsx";

import { useCmsStrings } from "../../core/hooks/use-cms-strings.js";
import { useCollection } from "../../collections/hooks/use-collection.js";
import { useCollectionCreate } from "../../collections/hooks/use-collection-create.js";
import { useCreateDraftRole } from "../../collections/hooks/use-draft-driver.js";

import { CollectionFieldsForm } from "../../collections/CollectionFieldsForm.jsx";
import { SlugField } from "../../collections/SlugField.jsx";
import { DetailPane } from "./DetailPane.jsx";
import { btnGhostStyle } from "../drawer-styles.js";
import {
  saveButtonStyle, createBarStyle, createButtonStyle, draftBadgeStyle,
  createFormWrapStyle, errorInlineStyle,
} from "./collection-styles.js";

/**
 * "+ Yeni" toolbar row. Lives inside the parallax list layer, so the create
 * pane itself renders separately in the panel's overlay slot; the two talk
 * through the shared list cache (the pending virtual row's `draftData` is the
 * stashed new-item draft).
 *
 * Names the language on a localized collection: the draft slot behind this row
 * is per locale, so the row says which one is about to be written before the
 * pane opens.
 *
 * @param {{
 *   collectionKey: string,
 *   listParams: import("../../shared/contracts/schemas.js").CollectionListParams,
 *   locale: string | null,
 *   onOpen: () => void,
 * }} props
 */
export function CreateButton({ collectionKey, listParams, locale, onOpen }) {
  const t = useCmsStrings();
  const { virtualItems } = useCollection(collectionKey, listParams);
  const hasServerDraft = virtualItems.some(
    (row) => row.origin === "pending" && row.draftData != null,
  );
  const label = locale
    ? t("collections.newRecordInLocale", { key: collectionKey, locale: locale.toUpperCase() })
    : t("collections.newRecordIn", { key: collectionKey });

  return (
    <div style={createBarStyle}>
      <button
        type="button"
        onClick={onOpen}
        className="inscribed-create-row"
        style={createButtonStyle}
      >
        <Plus size={14} />
        {label}
        {hasServerDraft ? <span style={draftBadgeStyle}>{t("collections.draftBadge")}</span> : null}
      </button>
    </div>
  );
}

/**
 * Create-mode detail pane. Mounts fresh per open: `useCollectionCreate` seeds
 * from the stashed backend draft (if any) and autosaves while mounted. Back
 * keeps the draft (autosaved); "Vazgeç" wipes it.
 *
 * A `UserDefined` collection also gets a slug input. The field is the only
 * thing that differs: the draft slot, its seeding and its autosave are the same
 * ones an AutoGenerated collection uses, and only the publish request splits.
 *
 * @param {{
 *   collectionKey: string,
 *   schema: import("../../shared/contracts/schemas.js").CollectionSchema,
 *   slugSource: import("../../shared/contracts/schemas.js").CollectionSlugSource,
 *   listParams: import("../../shared/contracts/schemas.js").CollectionListParams,
 *   translationOf?: string,
 *   locale?: string,
 *   onClose: () => void,
 * }} props
 */
export function CreatePane({ collectionKey, schema, slugSource, listParams, translationOf, locale, onClose }) {
  const t = useCmsStrings();
  // A page-level <CollectionComposer> may be open on the same collection, and
  // both would write its single new-item slot; the first to claim it wins.
  const scopeId = useId();
  const isDraftWriter = useCreateDraftRole(collectionKey, scopeId);
  // Lives here rather than in the hook: the backend's new-item draft slot has
  // no room for a slug, so this is the only copy and it dies with the pane.
  const [slug, setSlug] = useState("");
  const needsSlug = slugSource === "UserDefined";
  const {
    values,
    setValues,
    submit,
    deleteDraft,
    hasServerDraft,
    isPending,
    error,
  } = useCollectionCreate({
    collectionKey,
    schema,
    // Share the page's list window so the pending-row lookup hits the cache
    // instead of a separate GET.
    listParams,
    active: isDraftWriter,
    translationOf,
    locale,
    slug,
  });

  return (
    <DetailPane
      onBack={onClose}
      // Named whenever there is a language at all, not only for translations:
      // on a localized collection the whole point is knowing which one you are
      // composing in.
      title={locale
        ? t("collections.newRecordInLocale", { key: collectionKey, locale: locale.toUpperCase() })
        : t("collections.newRecordIn", { key: collectionKey })}
      meta={hasServerDraft ? <span style={draftBadgeStyle}>{t("collections.draftBadge")}</span> : null}
      footer={
        <>
          <button
            type="button"
            onClick={() => { deleteDraft(); onClose(); }}
            disabled={isPending}
            className="inscribed-btn-ghost"
            style={btnGhostStyle}
          >
            {t("status.discard")}
          </button>
          <span style={{ flex: 1 }} />
          <button
            type="button"
            onClick={() => submit(onClose)}
            disabled={isPending}
            className="inscribed-btn-collection"
            style={saveButtonStyle}
          >
            {isPending ? t("collections.creating") : t("collections.create")}
          </button>
        </>
      }
    >
      {/* Both take the drawer's palette explicitly: their own default is the
          portable one, for the host-page surfaces that reach them directly. */}
      <div style={createFormWrapStyle}>
        {needsSlug ? (
          <SlugField value={slug} onChange={setSlug} disabled={isPending} variant="drawer" />
        ) : null}
        <CollectionFieldsForm
          fields={schema.fields}
          values={values}
          onChange={setValues}
          disabled={isPending}
          variant="drawer"
        />
        {error ? <div style={errorInlineStyle}>{error}</div> : null}
      </div>
    </DetailPane>
  );
}
