"use client";

/**
 * @file The create lane: `CreateButton`, the pinned "+ Yeni" row inside the
 * parallax list layer, and `CreatePane`, the create-mode detail pane it opens.
 *
 * The two render in different slots of the panel and talk through the shared
 * list cache: the pending virtual row's `draftData` is what puts the draft
 * badge on the button.
 */

import { useId, useState } from "react";
import { Plus } from "../../shared/style/icons.jsx";

import { useCmsStrings } from "../../core/hooks/use-cms-strings.js";
import { useCollection } from "../../collections/hooks/use-collection.js";
import { useCollectionCreate } from "../../collections/hooks/use-collection-create.js";
import { useMultilingualCreate } from "../../collections/hooks/use-multilingual-create.js";
import { usePendingDrafts } from "../../collections/hooks/use-pending-drafts.js";
import { useCreateDraftRole } from "../../collections/hooks/use-draft-driver.js";

import { CollectionFieldsForm } from "../../collections/CollectionFieldsForm.jsx";
import { LanguageChips } from "../../collections/LanguageChips.jsx";
import { MultilingualFields } from "../../collections/MultilingualFields.jsx";
import { SlugField } from "../../collections/SlugField.jsx";
import { DetailPane } from "./DetailPane.jsx";
import { btnGhostStyle } from "../drawer-styles.js";
import {
  saveButtonStyle, createBarStyle, createButtonStyle, draftBadgeStyle,
  createFormWrapStyle, errorInlineStyle, createPlanStyle,
} from "./collection-styles.js";

/** Stable empty list, for a collection that holds one language or none. */
const NO_LANGUAGES = /** @type {string[]} */ ([]);

/**
 * "+ Yeni" toolbar row. Lives inside the parallax list layer, so the create
 * pane itself renders separately in the panel's overlay slot; the two talk
 * through the shared list cache (the pending virtual row's `draftData` is the
 * stashed new-item draft).
 *
 * Names the language on a collection that holds exactly one: the draft slot
 * behind this row is per locale, so the row says which one is about to be
 * written before the pane opens. A collection holding several leaves that to
 * the pane, which can write any of them.
 *
 * @param {{
 *   collectionKey: string,
 *   listParams: import("../../shared/contracts/schemas.js").CollectionListParams,
 *   locale: string | null,
 *   languages?: string[],
 *   onOpen: () => void,
 * }} props
 */
export function CreateButton({ collectionKey, listParams, locale, languages = NO_LANGUAGES, onOpen }) {
  const t = useCmsStrings();
  const multilingual = languages.length > 1;
  const { virtualItems } = useCollection(collectionKey, listParams);
  // Every language's slot on a multilingual collection, since the pane can
  // pick any of them up.
  const drafts = usePendingDrafts(collectionKey, multilingual ? languages : NO_LANGUAGES, listParams);
  const hasServerDraft = virtualItems.some((row) => row.origin === "pending" && row.draftData != null)
    || [...drafts.values()].some((draft) => draft != null);
  const label = locale && !multilingual
    ? t("collections.newRecordInLocale", { key: collectionKey, locale: locale.toUpperCase() })
    : t("collections.newRecordIn", { key: collectionKey });

  return (
    <div style={createBarStyle}>
      <button
        type="button"
        onClick={onOpen}
        className="inscribed-create-row"
        style={createButtonStyle}
      >
        <Plus size={14} />
        {label}
        {hasServerDraft ? <span style={draftBadgeStyle}>{t("collections.draftBadge")}</span> : null}
      </button>
    </div>
  );
}

/**
 * @typedef {Object} CreatePaneProps
 * @property {string} collectionKey
 * @property {import("../../shared/contracts/schemas.js").CollectionSchema} schema
 * @property {import("../../shared/contracts/schemas.js").CollectionSlugSource} slugSource
 * @property {import("../../shared/contracts/schemas.js").CollectionListParams} listParams
 * @property {string} [translationOf]
 * @property {string} [locale]
 * @property {string[]} [languages]  What the collection holds.
 * @property {() => void} onClose
 */

/**
 * Create-mode detail pane. Mounts fresh per open, seeds from the stashed
 * backend draft (if any) and autosaves while mounted. Back keeps the draft
 * (autosaved); "Vazgeç" wipes it.
 *
 * A collection holding several languages gets the multilingual form, unless
 * this is a translation of an existing record: that one names its target
 * language and its group, so there is nothing left to choose.
 *
 * @param {CreatePaneProps} props
 */
export function CreatePane(props) {
  const languages = props.languages ?? NO_LANGUAGES;
  return !props.translationOf && languages.length > 1
    ? <MultilingualCreatePane {...props} languages={languages} />
    : <SingleCreatePane {...props} />;
}

/**
 * One language. A `UserDefined` collection also gets a slug input. The field is
 * the only thing that differs: the draft slot, its seeding and its autosave are
 * the same ones an AutoGenerated collection uses, and only the publish request
 * splits.
 *
 * @param {CreatePaneProps} props
 */
function SingleCreatePane({ collectionKey, schema, slugSource, listParams, translationOf, locale, onClose }) {
  const t = useCmsStrings();
  // A page-level <CollectionComposer> may be open on the same collection, and
  // both would write its single new-item slot; the first to claim it wins.
  const scopeId = useId();
  const isDraftWriter = useCreateDraftRole(collectionKey, scopeId);
  // Lives here rather than in the hook: the backend's new-item draft slot has
  // no room for a slug, so this is the only copy and it dies with the pane.
  const [slug, setSlug] = useState("");
  const needsSlug = slugSource === "UserDefined";
  const {
    values,
    setValues,
    submit,
    deleteDraft,
    hasServerDraft,
    isPending,
    error,
  } = useCollectionCreate({
    collectionKey,
    schema,
    // Share the page's list window so the pending-row lookup hits the cache
    // instead of a separate GET.
    listParams,
    active: isDraftWriter,
    translationOf,
    locale,
    slug,
  });

  return (
    <DetailPane
      onBack={onClose}
      // Named whenever there is a language at all, not only for translations:
      // on a localized collection the whole point is knowing which one you are
      // composing in.
      title={locale
        ? t("collections.newRecordInLocale", { key: collectionKey, locale: locale.toUpperCase() })
        : t("collections.newRecordIn", { key: collectionKey })}
      meta={hasServerDraft ? <span style={draftBadgeStyle}>{t("collections.draftBadge")}</span> : null}
      footer={
        <>
          <button
            type="button"
            onClick={() => { deleteDraft(); onClose(); }}
            disabled={isPending}
            className="inscribed-btn-ghost"
            style={btnGhostStyle}
          >
            {t("status.discard")}
          </button>
          <span style={{ flex: 1 }} />
          <button
            type="button"
            onClick={() => submit(onClose)}
            disabled={isPending}
            className="inscribed-btn-collection"
            style={saveButtonStyle}
          >
            {isPending ? t("collections.creating") : t("collections.create")}
          </button>
        </>
      }
    >
      {/* Both take the drawer's palette explicitly: their own default is the
          portable one, for the host-page surfaces that reach them directly. */}
      <div style={createFormWrapStyle}>
        {needsSlug ? (
          <SlugField value={slug} onChange={setSlug} disabled={isPending} variant="drawer" />
        ) : null}
        <CollectionFieldsForm
          fields={schema.fields}
          values={values}
          onChange={setValues}
          disabled={isPending}
          variant="drawer"
        />
        {error ? <div style={errorInlineStyle}>{error}</div> : null}
      </div>
    </DetailPane>
  );
}

/**
 * Several languages. Opens on the panel's language and adds the others beside
 * it; one submit creates each as a translation of the first. A `UserDefined`
 * collection gets a slug per language, since every translation is its own row
 * at its own address.
 *
 * @param {CreatePaneProps & { languages: string[] }} props
 */
function MultilingualCreatePane({ collectionKey, schema, slugSource, listParams, locale, languages, onClose }) {
  const t = useCmsStrings();
  const scopeId = useId();
  const isDraftWriter = useCreateDraftRole(collectionKey, scopeId);
  const primary = locale && languages.includes(locale) ? locale : languages[0];
  const create = useMultilingualCreate({
    collectionKey, schema, languages, primary, listParams, active: isDraftWriter,
  });

  const codes = (/** @type {string[]} */ list) => list.map((l) => l.toUpperCase()).join(" + ");
  const open = create.added.filter((l) => create.statusOf(l).state !== "created");
  const retrying = open.length < create.added.length;
  const label = create.added.length > 1
    ? t(retrying ? "collections.retryLocales" : "collections.createLocales", { locales: codes(open) })
    : t("collections.create");

  return (
    <DetailPane
      onBack={onClose}
      title={t("collections.newRecordIn", { key: collectionKey })}
      meta={create.hasServerDraft ? <span style={draftBadgeStyle}>{t("collections.draftBadge")}</span> : null}
      footer={
        <>
          <button
            type="button"
            onClick={() => { create.discard(); onClose(); }}
            disabled={create.isPending}
            className="inscribed-btn-ghost"
            style={btnGhostStyle}
          >
            {t("status.discard")}
          </button>
          <span style={{ flex: 1 }} />
          <button
            type="button"
            onClick={() => create.submit(() => onClose())}
            disabled={create.isPending}
            className="inscribed-btn-collection"
            style={saveButtonStyle}
          >
            {create.isPending ? t("collections.creating") : label}
          </button>
        </>
      }
    >
      <div style={createFormWrapStyle}>
        <LanguageChips
          languages={languages}
          added={create.added}
          statusOf={create.statusOf}
          hasDraft={create.hasDraft}
          onAdd={create.add}
          onRemove={create.remove}
          disabled={create.isPending}
          variant="drawer"
        />
        <MultilingualFields
          fields={schema.fields}
          create={create}
          needsSlug={slugSource === "UserDefined"}
          variant="drawer"
        />
        {create.error ? <div style={errorInlineStyle}>{create.error}</div> : null}
        {create.added.length > 1 ? (
          <p style={createPlanStyle}>{t("collections.createPlan", { locales: codes(create.added) })}</p>
        ) : null}
      </div>
    </DetailPane>
  );
}
