"use client";

/**
 * @file `AdminCollectionRegionPanel`: drawer tab body for a collection with at
 * least one `<CollectionRegion>` binding on the page.
 *
 * Layout: a pinned "+ Yeni" toolbar row (when the collection supports
 * auto-generated slugs), then one quiet row-list per distinct region filter.
 * Rows don't expand inline; clicking one pushes a full-height detail pane in
 * from the right while the list layer parallax-slides left and dims (iOS-style
 * forward navigation). The list stays mounted underneath so caches and scroll
 * survive the round-trip.
 *
 * Each filter section owns its offset/limit and accumulates pages via "Load
 * more", using exactly the filter the region declared (filter parity).
 */

import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ChevronLeft, ChevronRight, Plus, Undo2 } from "./icons.jsx";

import { useCollectionContext } from "../lib/collection-context.js";
import { useStoreSelector } from "../lib/store.js";
import { useCollection } from "../hooks/use-collection.js";
import { useCollectionCreate } from "../hooks/use-collection-create.js";
import { useMyCollections } from "../hooks/use-my-collections.js";
import { NEW_DRAFT_GUID } from "../lib/schemas.js";
import { stableStringify } from "../lib/stable-stringify.js";

import {
  AdminCollectionEditor,
  useCollectionEditor,
  DraftIndicator,
} from "./AdminCollectionEditor.jsx";
import { CollectionFieldsForm } from "./editors/CollectionFieldsForm.jsx";
import {
  BG,
  BG_RAISED,
  TEXT,
  TEXT_MID,
  TEXT_MUTED,
  TEXT_FAINT,
  COLLECTION_ACCENT,
  COLLECTION_SOFT,
  COLLECTION_LINE,
  STATUS_DANGER,
  BORDER,
  HAIRLINE,
  SURFACE_1,
  FONT_MONO,
  FONT_SANS,
  RADIUS,
  R_BADGE,
  R_SM,
  R_BTN,
  buttonBaseStyle,
  paneStyle,
  emptyStateStyle,
  btnGhostStyle,
} from "./admin-drawer-styles.js";

const DEFAULT_DRAWER_PAGE_SIZE = 50;

// Shared by the pane slide-in and the list's parallax counter-slide so the two
// layers move in lockstep. The pane enters from the LEFT (the drawer's own
// anchor edge, so depth reads as coming out of the panel), the list recedes
// right.
const PANE_TRANSITION = { duration: 0.3, ease: [0.32, 0.72, 0.18, 1] };
// How far the list layer recedes while a pane is open.
const PARALLAX_SHIFT = "28%";

/**
 * @typedef {{ mode: "edit", slug: string } | { mode: "create" } | null} PaneState
 */

/**
 * Build a `useCollection` params object, omitting absent/zero keys the same way
 * `<CollectionRegion>` does, so the drawer's offset=0 window collapses onto the
 * page's cache entry instead of fetching its own.
 *
 * @param {Record<string, *> | undefined} filter
 * @param {number} offset
 * @param {number | undefined} limit
 * @returns {import("../lib/schemas.js").CollectionListParams}
 */
function buildListParams(filter, offset, limit) {
  return {
    ...(filter ? { filter } : {}),
    ...(offset ? { offset } : {}),
    ...(limit != null ? { limit } : {}),
  };
}

/**
 * @param {{ collectionKey: string }} props
 */
export function AdminCollectionRegionPanel({ collectionKey }) {
  const {
    collectionBindings,
    collectionStore,
    activeCollectionItem,
    setActiveCollectionItem,
  } = useCollectionContext();
  const { collections: my } = useMyCollections();

  const meta = my.find((c) => c.collectionKey === collectionKey) ?? null;
  const canCreate = Boolean(meta?.canCreate);
  const isAutoGenerated = meta?.slugSource === "AutoGenerated";
  const supportsCreate = canCreate && isAutoGenerated;

  const [pane, setPane] = useState(/** @type {PaneState} */ (null));

  // StatusBar "Aç" jump: consume the signal here and open the detail pane
  // directly. Pane-level fetch by slug means the jump works even when the
  // target sits past the loaded list window.
  useEffect(() => {
    if (!activeCollectionItem) return;
    if (activeCollectionItem.key !== collectionKey) return;
    setPane({ mode: "edit", slug: activeCollectionItem.slug });
    setActiveCollectionItem(null);
  }, [activeCollectionItem, collectionKey, setActiveCollectionItem]);

  // Per-slug dirty from the shared store (live overlay drafts + cached items
  // carrying server draftData), so rows don't each mount an editor hook.
  const drafts = useStoreSelector(collectionStore, (s) => s.drafts);
  const itemCache = useStoreSelector(collectionStore, (s) => s.itemCache);
  const dirtySlugs = useMemo(() => {
    /** @type {Set<string>} */
    const set = new Set();
    const prefix = `${collectionKey}:`;
    for (const key of drafts.keys()) {
      if (key.startsWith(prefix)) set.add(key.slice(prefix.length));
    }
    for (const [key, entry] of itemCache) {
      if (!key.startsWith(prefix)) continue;
      if (entry.item && entry.item.draftData != null) set.add(key.slice(prefix.length));
    }
    return set;
  }, [drafts, itemCache, collectionKey]);

  const sections = useMemo(() => {
    /** @type {Map<string, { filter: Record<string, *> | undefined, pageLimit: number | undefined, pageOffset: number | undefined }>} */
    const bySignature = new Map();
    for (const [, binding] of collectionBindings) {
      if (binding.slug) continue;
      if (binding.collection !== collectionKey) continue;
      const signature = stableStringify(binding.filter ?? null);
      if (bySignature.has(signature)) continue;
      bySignature.set(signature, {
        filter: binding.filter,
        pageLimit: binding.limit,
        pageOffset: binding.offset,
      });
    }
    return [...bySignature.entries()].map(([signature, info]) => ({ signature, ...info }));
  }, [collectionBindings, collectionKey]);

  // CreateLane reads the new-item draft sentinel from an unfiltered list
  // response. Reuse the unfiltered section's params if the page declares one,
  // else fall back to a dedicated unfiltered fetch.
  const createListParams = useMemo(() => {
    const unfiltered = sections.find((s) => s.filter === undefined);
    return buildListParams(undefined, unfiltered?.pageOffset ?? 0, unfiltered?.pageLimit);
  }, [sections]);

  const isPaneOpen = pane != null;

  return (
    // `position: relative` + `overflow: hidden` make the section the frame the
    // detail panes slide inside of.
    <section style={{ ...paneStyle, position: "relative", overflow: "hidden" }}>
      <motion.div
        initial={false}
        animate={isPaneOpen
          ? { x: PARALLAX_SHIFT, opacity: 0.4 }
          : { x: "0%", opacity: 1 }}
        transition={PANE_TRANSITION}
        style={{
          ...listLayerStyle,
          // The opaque pane covers the layer at rest; this only guards clicks
          // and tab focus during the transition frames.
          pointerEvents: isPaneOpen ? "none" : "auto",
        }}
        aria-hidden={isPaneOpen}
      >
        {supportsCreate && meta?.schema ? (
          <CreateButton
            collectionKey={collectionKey}
            listParams={createListParams}
            onOpen={() => setPane({ mode: "create" })}
          />
        ) : null}

        <div style={regionScrollStyle}>
          {sections.length === 0 ? (
            <div style={emptyStateStyle}>
              Bu sayfa <code>{collectionKey}</code> için bir region binding'i göstermiyor.
            </div>
          ) : (
            sections.map((section) => (
              <RegionSection
                key={section.signature}
                collectionKey={collectionKey}
                filter={section.filter}
                pageLimit={section.pageLimit}
                pageOffset={section.pageOffset}
                showHeader={sections.length > 1 || section.filter !== undefined}
                dirtySlugs={dirtySlugs}
                onOpenItem={(slug) => setPane({ mode: "edit", slug })}
              />
            ))
          )}
        </div>
      </motion.div>

      <AnimatePresence>
        {pane?.mode === "edit" ? (
          <ItemDetailPane
            key={`edit:${pane.slug}`}
            collectionKey={collectionKey}
            slug={pane.slug}
            onBack={() => setPane(null)}
          />
        ) : pane?.mode === "create" && meta?.schema ? (
          <CreatePane
            key="create"
            collectionKey={collectionKey}
            schema={meta.schema}
            listParams={createListParams}
            onClose={() => setPane(null)}
          />
        ) : null}
      </AnimatePresence>
    </section>
  );
}

const listLayerStyle = /** @type {React.CSSProperties} */ ({
  flex: 1,
  minHeight: 0,
  display: "flex",
  flexDirection: "column",
});

const regionScrollStyle = /** @type {React.CSSProperties} */ ({
  flex: 1,
  minHeight: 0,
  overflowY: "auto",
  scrollbarWidth: "none",
  paddingBottom: 16,
});

// ---------------------------------------------------------------------------
// Region section: humanized filter header + row list + load more
// ---------------------------------------------------------------------------

/**
 * @param {{
 *   collectionKey: string,
 *   filter: Record<string, *> | undefined,
 *   pageLimit: number | undefined,
 *   pageOffset: number | undefined,
 *   showHeader: boolean,
 *   dirtySlugs: Set<string>,
 *   onOpenItem: (slug: string) => void,
 * }} props
 */
function RegionSection({
  collectionKey, filter, pageLimit, pageOffset, showHeader, dirtySlugs, onOpenItem,
}) {
  const initialLimit = pageLimit ?? DEFAULT_DRAWER_PAGE_SIZE;
  const initialOffset = pageOffset ?? 0;
  const [offset, setOffset] = useState(initialOffset);
  const [limit] = useState(initialLimit);

  const filterKey = stableStringify(filter ?? null);
  const [accumulated, setAccumulated] = useState(
    /** @type {import("../lib/schemas.js").CollectionItemResponse[]} */ ([]),
  );

  const params = useMemo(
    () => buildListParams(filter, offset, limit),
    [filter, offset, limit],
  );
  const { items, total, isLoading, error, refetch } = useCollection(collectionKey, params);

  useEffect(() => {
    setOffset(initialOffset);
    setAccumulated([]);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filterKey]);

  useEffect(() => {
    if (isLoading || error) return;
    // Drop only the slug-less new-item sentinel (AutoGenerated's create draft).
    // A boot-GUID row that carries a slug is a RoleDerived virtual item, the
    // user's own editable row, so it stays and renders as a normal row.
    const real = items.filter((row) => row.id !== NEW_DRAFT_GUID || row.slug);
    if (offset === initialOffset) {
      setAccumulated(real);
    } else {
      setAccumulated((prev) => {
        const seen = new Set(prev.map((row) => row.slug));
        return [...prev, ...real.filter((row) => !seen.has(row.slug))];
      });
    }
  }, [items, isLoading, error, offset, initialOffset]);

  const canLoadMore = accumulated.length < total;
  const loadMore = () => setOffset((o) => o + limit);
  const remaining = Math.max(0, total - accumulated.length);

  return (
    <div style={sectionWrapStyle}>
      {showHeader ? (
        <RegionHeader filter={filter} loaded={accumulated.length} total={total} />
      ) : null}

      {error ? (
        <div style={errorBoxStyle}>
          <span style={{ flex: 1 }}>Liste alınamadı: {error.message}</span>
          <button
            type="button"
            onClick={refetch}
            className="inscribed-text-button"
            style={retryTextStyle}
          >
            Yeniden dene
          </button>
        </div>
      ) : isLoading && accumulated.length === 0 ? (
        <div style={emptyStateStyle}>Yükleniyor…</div>
      ) : accumulated.length === 0 ? (
        <div style={emptyStateStyle}>Bu filtre için kayıt yok.</div>
      ) : (
        <ul style={rowGroupStyle} data-cms-list>
          {accumulated.map((item) => (
            <li key={item.slug} style={{ listStyle: "none" }}>
              <RegionItemRow
                slug={item.slug}
                canEdit={item.canEdit}
                dirty={dirtySlugs.has(item.slug)}
                onOpen={() => onOpenItem(item.slug)}
              />
            </li>
          ))}
        </ul>
      )}

      {canLoadMore ? (
        <button
          type="button"
          onClick={loadMore}
          disabled={isLoading}
          className="inscribed-load-more"
          style={loadMoreStyle}
        >
          {isLoading ? "Yükleniyor…" : `Daha fazla yükle (${remaining} kalan)`}
        </button>
      ) : null}
    </div>
  );
}

/**
 * Humanized section header: one chip per filter entry ("Tümü" when
 * unfiltered), loaded/total count right-aligned.
 *
 * @param {{ filter: Record<string, *> | undefined, loaded: number, total: number }} props
 */
function RegionHeader({ filter, loaded, total }) {
  const entries = filter ? Object.entries(filter) : [];
  return (
    <div style={regionHeaderStyle}>
      {entries.length === 0 ? (
        <span style={regionAllLabelStyle}>Tümü</span>
      ) : (
        entries.map(([key, value]) => (
          <span key={key} style={filterChipStyle}>
            <span style={filterChipKeyStyle}>{key}</span>
            <span style={filterChipValueStyle}>{String(value)}</span>
          </span>
        ))
      )}
      <span style={regionCountStyle}>{loaded} / {total}</span>
    </div>
  );
}

/**
 * One collection item as a quiet list row: slug, readonly chip, dirty dot,
 * trailing chevron. All editing happens in the detail pane.
 *
 * @param {{ slug: string, canEdit: boolean, dirty: boolean, onOpen: () => void }} props
 */
function RegionItemRow({ slug, canEdit, dirty, onOpen }) {
  return (
    <button
      type="button"
      onClick={onOpen}
      className="inscribed-region-row"
      style={rowStyle}
    >
      <span style={rowSlugStyle} title={slug}>{slug}</span>
      {!canEdit ? <span style={readonlyChipStyle}>readonly</span> : null}
      {dirty ? (
        <span style={rowDirtyDotStyle} aria-label="Kaydedilmemiş değişiklik" />
      ) : null}
      <span className="inscribed-region-row-chevron" style={rowChevronStyle} aria-hidden="true">
        <ChevronRight size={13} />
      </span>
    </button>
  );
}

// ---------------------------------------------------------------------------
// Detail pane shell (shared by edit + create)
// ---------------------------------------------------------------------------

/**
 * Full-height pane sliding in from the right over the row list. Back header on
 * top, scrollable body, optional pinned action footer. Escape goes back.
 *
 * @param {{
 *   onBack: () => void,
 *   title: string,
 *   meta?: React.ReactNode,
 *   footer?: React.ReactNode,
 *   children: React.ReactNode,
 * }} props
 */
function DetailPane({ onBack, title, meta, footer, children }) {
  useEffect(() => {
    /** @param {KeyboardEvent} e */
    const onKeyDown = (e) => {
      if (e.key === "Escape") onBack();
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [onBack]);

  return (
    <motion.div
      initial={{ x: "-100%" }}
      animate={{ x: 0 }}
      exit={{ x: "-100%" }}
      transition={PANE_TRANSITION}
      style={detailPaneStyle}
      role="region"
      aria-label={title}
    >
      <header style={detailHeaderStyle}>
        <button
          type="button"
          onClick={onBack}
          className="inscribed-pane-back"
          style={paneBackStyle}
          aria-label="Listeye dön"
          title="Listeye dön (Esc)"
        >
          <ChevronLeft size={15} />
        </button>
        <span style={detailTitleStyle} title={title}>{title}</span>
        {meta}
      </header>
      <div style={detailBodyStyle}>{children}</div>
      {footer ? <footer style={detailFooterStyle}>{footer}</footer> : null}
    </motion.div>
  );
}

/**
 * Detail pane for one existing (or RoleDerived virtual) collection row.
 * `useCollectionEditor` is lifted here so the footer actions and the form body
 * share one state.
 *
 * @param {{ collectionKey: string, slug: string, onBack: () => void }} props
 */
function ItemDetailPane({ collectionKey, slug, onBack }) {
  const editor = useCollectionEditor(collectionKey, slug);
  const isDirty = editor.hasDraft && editor.canEdit;

  return (
    <DetailPane
      onBack={onBack}
      title={slug}
      meta={
        <>
          {editor.item && !editor.canEdit ? (
            <span style={readonlyChipStyle}>readonly</span>
          ) : null}
          {editor.item ? (
            <span style={detailVersionStyle}>
              {editor.isVirtual ? "yeni" : `v${editor.item.version}`}
            </span>
          ) : null}
        </>
      }
      footer={editor.canEdit ? (
        <>
          <DraftIndicator
            status={editor.draftStatus}
            lastSavedAt={editor.lastDraftSavedAt}
            hasServerDraft={editor.item?.draftData != null}
            publishedFlash={editor.publishedFlash}
          />
          <span style={{ flex: 1 }} />
          {isDirty ? (
            <button
              type="button"
              onClick={editor.undoDraft}
              disabled={editor.isPending}
              className="inscribed-btn-ghost"
              style={btnGhostStyle}
              aria-label="Bu kaydın değişikliklerini geri al"
              title="Geri al"
            >
              <Undo2 size={13} />
            </button>
          ) : null}
          <button
            type="button"
            onClick={editor.save}
            disabled={editor.isPending}
            className="inscribed-btn-collection"
            style={saveButtonStyle}
          >
            {editor.isPending ? "Kaydediliyor…" : "Kaydet"}
          </button>
        </>
      ) : null}
    >
      <AdminCollectionEditor editor={editor} showMetaRow={false} showActions={false} />
    </DetailPane>
  );
}

// ---------------------------------------------------------------------------
// Create: pinned toolbar row (list layer) + create-mode detail pane (overlay)
// ---------------------------------------------------------------------------

/**
 * "+ Yeni" toolbar row for AutoGenerated collections. Lives inside the
 * parallax list layer, so the create pane itself renders separately in the
 * panel's overlay slot; the two talk through the shared list cache (the
 * slug-less sentinel row's `draftData` is the stashed new-item draft).
 *
 * @param {{
 *   collectionKey: string,
 *   listParams: import("../lib/schemas.js").CollectionListParams,
 *   onOpen: () => void,
 * }} props
 */
function CreateButton({ collectionKey, listParams, onOpen }) {
  const { items } = useCollection(collectionKey, listParams);
  const hasServerDraft = items.some(
    (row) => row.id === NEW_DRAFT_GUID && !row.slug && row.draftData != null,
  );

  return (
    <div style={createBarStyle}>
      <button
        type="button"
        onClick={onOpen}
        className="inscribed-create-row"
        style={createButtonStyle}
      >
        <Plus size={13} />
        <span style={{ flex: 1 }}>Yeni {collectionKey}</span>
        {hasServerDraft ? <span style={draftBadgeStyle}>taslak</span> : null}
      </button>
    </div>
  );
}

/**
 * Create-mode detail pane. Mounts fresh per open: `useCollectionCreate` seeds
 * from the stashed backend draft (if any) and autosaves while mounted. Back
 * keeps the draft (autosaved); "Vazgeç" wipes it.
 *
 * @param {{
 *   collectionKey: string,
 *   schema: import("../lib/schemas.js").CollectionSchema,
 *   listParams: import("../lib/schemas.js").CollectionListParams,
 *   onClose: () => void,
 * }} props
 */
function CreatePane({ collectionKey, schema, listParams, onClose }) {
  const {
    values,
    setValues,
    submit,
    deleteDraft,
    hasServerDraft,
    isPending,
    error,
  } = useCollectionCreate({
    collectionKey,
    schema,
    // Share the page's list window so the sentinel lookup hits the cache
    // instead of a separate GET.
    listParams,
  });

  return (
    <DetailPane
      onBack={onClose}
      title={`Yeni ${collectionKey}`}
      meta={hasServerDraft ? <span style={draftBadgeStyle}>taslak</span> : null}
      footer={
        <>
          <button
            type="button"
            onClick={() => { deleteDraft(); onClose(); }}
            disabled={isPending}
            className="inscribed-btn-ghost"
            style={btnGhostStyle}
          >
            Vazgeç
          </button>
          <span style={{ flex: 1 }} />
          <button
            type="button"
            onClick={() => submit(onClose)}
            disabled={isPending}
            className="inscribed-btn-collection"
            style={saveButtonStyle}
          >
            {isPending ? "Oluşturuluyor…" : "Oluştur"}
          </button>
        </>
      }
    >
      <div style={createFormWrapStyle}>
        <CollectionFieldsForm
          fields={schema.fields}
          values={values}
          onChange={setValues}
          disabled={isPending}
        />
        {error ? <div style={errorInlineStyle}>{error}</div> : null}
      </div>
    </DetailPane>
  );
}

// ---- Styles ----------------------------------------------------------------

const sectionWrapStyle = /** @type {React.CSSProperties} */ ({
  display: "flex",
  flexDirection: "column",
  gap: 6,
  marginBottom: 4,
});

const regionHeaderStyle = /** @type {React.CSSProperties} */ ({
  display: "flex",
  alignItems: "center",
  flexWrap: "wrap",
  gap: 6,
  padding: "14px 16px 4px",
});

const regionAllLabelStyle = /** @type {React.CSSProperties} */ ({
  font: `600 10.5px/1 ${FONT_SANS}`,
  letterSpacing: "0.08em",
  textTransform: "uppercase",
  color: TEXT_MUTED,
});

const filterChipStyle = /** @type {React.CSSProperties} */ ({
  display: "inline-flex",
  alignItems: "center",
  gap: 5,
  padding: "3px 7px",
  borderRadius: R_BADGE,
  background: SURFACE_1,
  boxShadow: `inset 0 0 0 1px ${HAIRLINE}`,
  font: `500 10.5px/1 ${FONT_MONO}`,
});

const filterChipKeyStyle = /** @type {React.CSSProperties} */ ({
  color: TEXT_FAINT,
});

const filterChipValueStyle = /** @type {React.CSSProperties} */ ({
  color: TEXT_MID,
});

const regionCountStyle = /** @type {React.CSSProperties} */ ({
  marginLeft: "auto",
  font: `500 10.5px/1 ${FONT_MONO}`,
  color: TEXT_FAINT,
});

const rowGroupStyle = /** @type {React.CSSProperties} */ ({
  margin: "0 16px",
  padding: 0,
  borderRadius: RADIUS,
  boxShadow: `inset 0 0 0 1px ${HAIRLINE}`,
  overflow: "hidden",
});

const rowStyle = /** @type {React.CSSProperties} */ ({
  display: "flex",
  alignItems: "center",
  gap: 8,
  width: "100%",
  padding: "10px 12px",
  border: 0,
  cursor: "pointer",
  textAlign: "left",
  fontFamily: "inherit",
  color: "inherit",
});

const rowSlugStyle = /** @type {React.CSSProperties} */ ({
  flex: 1,
  minWidth: 0,
  font: `500 12px/1.2 ${FONT_MONO}`,
  color: TEXT,
  whiteSpace: "nowrap",
  overflow: "hidden",
  textOverflow: "ellipsis",
});

const rowDirtyDotStyle = /** @type {React.CSSProperties} */ ({
  width: 6,
  height: 6,
  borderRadius: "50%",
  background: COLLECTION_ACCENT,
  boxShadow: `0 0 5px color-mix(in srgb, ${COLLECTION_ACCENT} 50%, transparent)`,
  flexShrink: 0,
});

const rowChevronStyle = /** @type {React.CSSProperties} */ ({
  display: "inline-flex",
  color: TEXT_FAINT,
  flexShrink: 0,
});

const readonlyChipStyle = /** @type {React.CSSProperties} */ ({
  color: TEXT_MUTED,
  textTransform: "uppercase",
  fontSize: 9,
  padding: "1px 6px",
  background: SURFACE_1,
  borderRadius: 3,
  letterSpacing: "0.05em",
  flexShrink: 0,
});

const errorBoxStyle = /** @type {React.CSSProperties} */ ({
  margin: "0 16px 4px",
  display: "flex",
  alignItems: "center",
  gap: 8,
  color: `color-mix(in srgb, ${STATUS_DANGER} 55%, var(--ins-text, #fff))`,
  fontSize: 12,
  padding: "8px 10px",
  background: `color-mix(in srgb, ${STATUS_DANGER} 8%, transparent)`,
  border: `1px solid color-mix(in srgb, ${STATUS_DANGER} 25%, transparent)`,
  borderRadius: R_SM,
});

const retryTextStyle = /** @type {React.CSSProperties} */ ({
  background: "transparent",
  color: TEXT_MUTED,
  border: 0,
  borderRadius: R_BADGE,
  padding: "4px 8px",
  cursor: "pointer",
  fontSize: 11,
  fontFamily: FONT_SANS,
});

const loadMoreStyle = /** @type {React.CSSProperties} */ ({
  alignSelf: "center",
  margin: "4px auto 12px",
  padding: "7px 16px",
  background: "transparent",
  color: TEXT_MUTED,
  border: `1px solid ${BORDER}`,
  borderRadius: R_BTN,
  cursor: "pointer",
  font: `12px ${FONT_SANS}`,
  fontFamily: FONT_SANS,
});

// -- Detail pane --

// No z-index on purpose: DOM order already stacks the pane above the list
// layer, and any z here would lift the pane over the drawer handle's 4px
// overlap at the panel edge (the handle must keep painting on top).
const detailPaneStyle = /** @type {React.CSSProperties} */ ({
  position: "absolute",
  inset: 0,
  display: "flex",
  flexDirection: "column",
  background: BG,
  // Right-edge hairline + soft cast shadow (the pane enters from the left):
  // separates the pane from the receding list layer while the two slide.
  boxShadow: `1px 0 0 ${HAIRLINE}, 16px 0 36px rgba(0, 0, 0, 0.35)`,
});

const detailHeaderStyle = /** @type {React.CSSProperties} */ ({
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "9px 16px",
  borderBottom: `1px solid ${HAIRLINE}`,
  flexShrink: 0,
});

const paneBackStyle = /** @type {React.CSSProperties} */ ({
  width: 24,
  height: 24,
  marginLeft: -6,
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  borderRadius: R_SM,
  border: 0,
  cursor: "pointer",
  padding: 0,
  flexShrink: 0,
});

const detailTitleStyle = /** @type {React.CSSProperties} */ ({
  flex: 1,
  minWidth: 0,
  font: `500 12.5px/1.2 ${FONT_MONO}`,
  color: TEXT,
  whiteSpace: "nowrap",
  overflow: "hidden",
  textOverflow: "ellipsis",
});

const detailVersionStyle = /** @type {React.CSSProperties} */ ({
  font: `500 11px/1 ${FONT_MONO}`,
  color: TEXT_MUTED,
  flexShrink: 0,
});

const detailBodyStyle = /** @type {React.CSSProperties} */ ({
  flex: 1,
  minHeight: 0,
  overflowY: "auto",
  scrollbarWidth: "none",
  padding: "14px 16px 16px",
});

const detailFooterStyle = /** @type {React.CSSProperties} */ ({
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "10px 16px",
  borderTop: `1px solid ${HAIRLINE}`,
  background: BG_RAISED,
  flexShrink: 0,
});

const saveButtonStyle = /** @type {React.CSSProperties} */ ({
  ...buttonBaseStyle,
  fontWeight: 600,
});

// -- Create lane --

const createBarStyle = /** @type {React.CSSProperties} */ ({
  padding: "10px 16px 4px",
  flexShrink: 0,
});

const createButtonStyle = /** @type {React.CSSProperties} */ ({
  display: "flex",
  alignItems: "center",
  gap: 8,
  width: "100%",
  padding: "8px 10px",
  background: "transparent",
  border: 0,
  borderRadius: R_BTN,
  color: TEXT_MID,
  font: `500 12px/1 ${FONT_SANS}`,
  cursor: "pointer",
  textAlign: "left",
  fontFamily: FONT_SANS,
});

const draftBadgeStyle = /** @type {React.CSSProperties} */ ({
  font: `600 9px/1 ${FONT_MONO}`,
  letterSpacing: "0.06em",
  textTransform: "uppercase",
  padding: "3px 6px",
  borderRadius: R_BADGE,
  background: COLLECTION_SOFT,
  color: COLLECTION_ACCENT,
  boxShadow: `inset 0 0 0 1px ${COLLECTION_LINE}`,
  flexShrink: 0,
});

const createFormWrapStyle = /** @type {React.CSSProperties} */ ({
  display: "flex",
  flexDirection: "column",
  gap: 12,
});

const errorInlineStyle = /** @type {React.CSSProperties} */ ({
  color: `color-mix(in srgb, ${STATUS_DANGER} 55%, var(--ins-text, #fff))`,
  fontSize: 12,
  padding: "8px 10px",
  background: `color-mix(in srgb, ${STATUS_DANGER} 10%, transparent)`,
  border: `1px solid color-mix(in srgb, ${STATUS_DANGER} 30%, transparent)`,
  borderRadius: R_SM,
});
