"use client";

/**
 * @file `AdminCollectionRegionPanel` - drawer body for a
 * `<CollectionRegion>` binding. Mirrors what the page renders (same
 * cached list) but exposes per-item editors and, when the collection
 * supports it, a "+ Yeni" create form.
 *
 * Tab visibility is decided upstream in `AdminDrawer` from the
 * registry + /me intersection; this component assumes the user has
 * access to the collection (otherwise the tab wouldn't have opened).
 */

import { useState, useTransition } from "react";
import { motion } from "framer-motion";
import { ChevronDown, Plus } from "lucide-react";

import { useCmsContext } from "../lib/context.js";
import { useCollection } from "../hooks/use-collection.js";
import { useMyCollections } from "../hooks/use-my-collections.js";
import { createCollectionItem, CmsApiError } from "../lib/api-client.js";

import { AdminCollectionEditor } from "./AdminCollectionEditor.jsx";
import {
  CollectionFieldsForm,
  seedValues,
  buildPayload,
  requiredMissing,
} from "./editors/CollectionFieldsForm.jsx";
import {
  ACCENT,
  TEXT_MUTED,
  paneStyle,
  listStyle,
  emptyStateStyle,
  blockCardStyle,
  blockHeaderStyle,
  blockBodyStyle,
  COLLECTION_CARD_BORDER,
  COLLECTION_CARD_ACTIVE_BORDER,
} from "./admin-drawer-styles.js";

/**
 * @param {{ collectionKey: string }} props
 */
export function AdminCollectionRegionPanel({ collectionKey }) {
  const { collections: my } = useMyCollections();
  const { items, isLoading, error } = useCollection(collectionKey);

  const meta = my.find((c) => c.collectionKey === collectionKey) ?? null;
  const canCreate = Boolean(meta?.canCreate);
  const isAutoGenerated = meta?.slugSource === "AutoGenerated";
  const supportsCreate = canCreate && isAutoGenerated;

  return (
    <section style={paneStyle}>
      {supportsCreate && meta?.schema ? (
        <CreateForm collectionKey={collectionKey} schema={meta.schema} />
      ) : null}

      {error ? (
        <div style={errorStyle}>Liste alınamadı: {error.message}</div>
      ) : isLoading ? (
        <div style={emptyStateStyle}>Yükleniyor…</div>
      ) : items.length === 0 ? (
        <div style={emptyStateStyle}>
          Henüz kayıt yok{supportsCreate ? " — yukarıdaki formla başlayabilirsin." : "."}
        </div>
      ) : (
        <ul style={listStyle} data-cms-list>
          {items.map((item) => (
            <li key={item.id || item.slug} style={{ listStyle: "none" }}>
              <RegionItemCard collectionKey={collectionKey} slug={item.slug} canEdit={item.canEdit} />
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

/**
 * @param {{ collectionKey: string, slug: string, canEdit: boolean }} props
 */
function RegionItemCard({ collectionKey, slug, canEdit }) {
  const [isOpen, setIsOpen] = useState(false);
  const cardStyle = {
    ...blockCardStyle,
    border: isOpen ? COLLECTION_CARD_ACTIVE_BORDER : COLLECTION_CARD_BORDER,
  };

  return (
    <div style={cardStyle}>
      <button
        type="button"
        onClick={() => setIsOpen((v) => !v)}
        style={{
          ...blockHeaderStyle,
          background: "transparent",
          border: "none",
          width: "100%",
          textAlign: "left",
          cursor: "pointer",
          userSelect: "none",
          fontFamily: "inherit",
        }}
      >
        <span style={slugStyle}>{slug}</span>
        {!canEdit ? <span style={readonlyChipStyle}>readonly</span> : null}
        <motion.span
          initial={false}
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
          style={{ display: "inline-flex", color: TEXT_MUTED, marginLeft: "auto" }}
        >
          <ChevronDown size={14} />
        </motion.span>
      </button>

      {/* display:none so the AdminCollectionEditor stays mounted across
          collapse and its cache subscriptions don't refire fetches. */}
      <div style={{ display: isOpen ? "block" : "none" }}>
        <div style={blockBodyStyle}>
          <AdminCollectionEditor
            collection={collectionKey}
            slug={slug}
            showMetaRow={false}
          />
        </div>
      </div>
    </div>
  );
}

/**
 * @param {{ collectionKey: string, schema: import("../lib/schemas.js").CollectionSchema }} props
 */
function CreateForm({ collectionKey, schema }) {
  const { config, getAccessToken, updateCollectionItem } = useCmsContext();
  const [isOpen, setIsOpen] = useState(false);
  const [values, setValues] = useState(() => seedValues(schema.fields, {}));
  const [error, setError] = useState(/** @type {string | null} */ (null));
  const [isPending, startTransition] = useTransition();

  const reset = () => {
    setValues(seedValues(schema.fields, {}));
    setError(null);
  };

  const submit = () => {
    setError(null);
    const missing = requiredMissing(schema.fields, values);
    if (missing) {
      setError(`Zorunlu alan eksik: ${missing}`);
      return;
    }
    startTransition(async () => {
      try {
        const token = await getAccessToken();
        const init = token ? { headers: { Authorization: `Bearer ${token}` } } : undefined;
        const created = await createCollectionItem(
          config,
          collectionKey,
          { data: buildPayload(schema.fields, values) },
          init,
        );
        // updateCollectionItem also patches the list cache (item appended
        // if missing), so the row appears below without a refetch.
        updateCollectionItem(collectionKey, created.slug, created);
        reset();
        setIsOpen(false);
      } catch (err) {
        if (err instanceof CmsApiError && err.isForbidden) {
          setError("Bu collection'da kayıt oluşturma yetkin yok.");
        } else if (err instanceof CmsApiError && err.status === 400) {
          setError(`Geçersiz veri: ${err.detail || err.message}`);
        } else {
          setError(/** @type {Error} */ (err).message);
        }
      }
    });
  };

  return (
    <div style={createCardStyle}>
      <button
        type="button"
        onClick={() => setIsOpen((v) => !v)}
        style={createToggleStyle}
      >
        <Plus size={14} />
        <span>Yeni {collectionKey.toLowerCase()} ekle</span>
        <motion.span
          initial={false}
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
          style={{ display: "inline-flex", color: TEXT_MUTED, marginLeft: "auto" }}
        >
          <ChevronDown size={13} />
        </motion.span>
      </button>

      <div style={{ display: isOpen ? "block" : "none" }}>
        <div style={{ padding: "10px 14px 14px", display: "flex", flexDirection: "column", gap: 10 }}>
          <CollectionFieldsForm
            fields={schema.fields}
            values={values}
            onChange={setValues}
            disabled={isPending}
          />
          {error ? <div style={errorStyle}>{error}</div> : null}
          <div style={{ display: "flex", gap: 8 }}>
            <button
              type="button"
              onClick={submit}
              disabled={isPending}
              style={primaryButtonStyle}
            >
              {isPending ? "Oluşturuluyor…" : "Oluştur"}
            </button>
            <button
              type="button"
              onClick={() => { setIsOpen(false); reset(); }}
              disabled={isPending}
              style={secondaryButtonStyle}
            >
              İptal
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ---- Styles --------------------------------------------------------------

const slugStyle = /** @type {React.CSSProperties} */ ({
  fontFamily: "ui-monospace, 'SF Mono', monospace",
  fontSize: 12,
  color: "rgba(255,255,255,0.85)",
  letterSpacing: "0.02em",
});

const readonlyChipStyle = /** @type {React.CSSProperties} */ ({
  color: TEXT_MUTED,
  textTransform: "uppercase",
  fontSize: 9,
  padding: "1px 6px",
  background: "rgba(255,255,255,0.05)",
  borderRadius: 3,
  letterSpacing: "0.05em",
  marginLeft: 8,
});

const errorStyle = /** @type {React.CSSProperties} */ ({
  color: "#ff8b8b",
  fontSize: 12,
  padding: "6px 10px",
  background: "rgba(226,100,100,0.10)",
  border: "1px solid rgba(226,100,100,0.30)",
  borderRadius: 3,
});

const createCardStyle = /** @type {React.CSSProperties} */ ({
  border: "1px dashed rgba(140, 130, 210, 0.35)",
  borderRadius: 6,
  background: "rgba(140, 130, 210, 0.04)",
  marginBottom: 12,
  overflow: "hidden",
});

const createToggleStyle = /** @type {React.CSSProperties} */ ({
  width: "100%",
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "10px 14px",
  background: "transparent",
  border: "none",
  cursor: "pointer",
  color: "rgb(190, 180, 230)",
  fontSize: 12,
  fontWeight: 500,
  fontFamily: "inherit",
  letterSpacing: "0.02em",
});

const primaryButtonStyle = /** @type {React.CSSProperties} */ ({
  padding: "6px 14px",
  background: ACCENT,
  color: "#221d18",
  border: "none",
  borderRadius: 3,
  cursor: "pointer",
  fontSize: 12,
  fontWeight: 600,
  fontFamily: "inherit",
});

const secondaryButtonStyle = /** @type {React.CSSProperties} */ ({
  padding: "6px 14px",
  background: "transparent",
  color: TEXT_MUTED,
  border: "1px solid rgba(255,255,255,0.15)",
  borderRadius: 3,
  cursor: "pointer",
  fontSize: 12,
  fontFamily: "inherit",
});
