"use client";

/**
 * @file `AdminCollectionRegionPanel` - drawer tab body for a collection
 * that has at least one `<CollectionRegion>` binding on the current
 * page. Renders one sub-section per distinct filter on the page so a
 * page with two regions (`featured=true` + `tags=release`) shows both
 * lists side by side. A single shared "+ Yeni" form lives at the top
 * when the collection supports auto-generated slug creation.
 *
 * Each sub-section drives its own offset/limit state and accumulates
 * pages via "Load more". Filter parity with the page is enforced (the
 * panel uses exactly the filter the `<CollectionRegion>` declared);
 * limit/offset start at the page's values but the drawer extends
 * independently so the admin can paginate past the page's window.
 */

import { useEffect, useMemo, useState, useTransition } from "react";
import { motion } from "framer-motion";
import { ChevronDown, Plus } from "lucide-react";

import { useCmsContext } from "../lib/context.js";
import { useCollection } from "../hooks/use-collection.js";
import { useMyCollections } from "../hooks/use-my-collections.js";
import { createCollectionItem, CmsApiError } from "../lib/api-client.js";
import { stableStringify } from "../lib/stable-stringify.js";

import { AdminCollectionEditor } from "./AdminCollectionEditor.jsx";
import {
  CollectionFieldsForm,
  seedValues,
  buildPayload,
  requiredMissing,
} from "./editors/CollectionFieldsForm.jsx";
import {
  ACCENT,
  TEXT_MUTED,
  paneStyle,
  listStyle,
  emptyStateStyle,
  blockCardStyle,
  blockHeaderStyle,
  blockBodyStyle,
  COLLECTION_CARD_BORDER,
  COLLECTION_CARD_ACTIVE_BORDER,
} from "./admin-drawer-styles.js";

const DEFAULT_DRAWER_PAGE_SIZE = 50;

/**
 * @param {{ collectionKey: string }} props
 */
export function AdminCollectionRegionPanel({ collectionKey }) {
  const { collectionBindings } = useCmsContext();
  const { collections: my } = useMyCollections();

  const meta = my.find((c) => c.collectionKey === collectionKey) ?? null;
  const canCreate = Boolean(meta?.canCreate);
  const isAutoGenerated = meta?.slugSource === "AutoGenerated";
  const supportsCreate = canCreate && isAutoGenerated;

  // One sub-section per unique filter the page declared. Sections keep
  // a stable order (Map insertion order), so the user sees them in the
  // order the regions render on the page.
  const sections = useMemo(() => {
    /** @type {Map<string, { filter: Record<string, *> | undefined, pageLimit: number | undefined, pageOffset: number | undefined }>} */
    const bySignature = new Map();
    for (const [, binding] of collectionBindings) {
      if (binding.slug) continue; // skip Item bindings (Page tab)
      if (binding.collection !== collectionKey) continue;
      const signature = stableStringify(binding.filter ?? null);
      if (bySignature.has(signature)) continue;
      bySignature.set(signature, {
        filter: binding.filter,
        pageLimit: binding.limit,
        pageOffset: binding.offset,
      });
    }
    return [...bySignature.entries()].map(([signature, info]) => ({ signature, ...info }));
  }, [collectionBindings, collectionKey]);

  return (
    <section style={paneStyle}>
      {supportsCreate && meta?.schema ? (
        <CreateForm collectionKey={collectionKey} schema={meta.schema} />
      ) : null}

      {sections.length === 0 ? (
        <div style={emptyStateStyle}>
          Bu sayfa <code>{collectionKey}</code> için bir region binding'i göstermiyor.
        </div>
      ) : (
        sections.map((section) => (
          <RegionSection
            key={section.signature}
            collectionKey={collectionKey}
            filter={section.filter}
            pageLimit={section.pageLimit}
            pageOffset={section.pageOffset}
            showHeader={sections.length > 1 || section.filter !== undefined}
          />
        ))
      )}
    </section>
  );
}

/**
 * @param {{
 *   collectionKey: string,
 *   filter: Record<string, *> | undefined,
 *   pageLimit: number | undefined,
 *   pageOffset: number | undefined,
 *   showHeader: boolean,
 * }} props
 */
function RegionSection({ collectionKey, filter, pageLimit, pageOffset, showHeader }) {
  // Drawer owns its own offset/limit window: starts at the page's
  // values (filter parity) but grows independently via "Load more".
  const initialLimit = pageLimit ?? DEFAULT_DRAWER_PAGE_SIZE;
  const initialOffset = pageOffset ?? 0;
  const [offset, setOffset] = useState(initialOffset);
  const [limit] = useState(initialLimit);

  // Accumulated items across "Load more" presses. Reset whenever the
  // filter identity changes or the cache is invalidated (e.g. by a
  // save) - we detect the latter by watching for an empty/null entry
  // on what should be a populated fetch.
  const filterKey = stableStringify(filter ?? null);
  const [accumulated, setAccumulated] = useState(
    /** @type {import("../lib/schemas.js").CollectionItemResponse[]} */ ([]),
  );

  const params = useMemo(
    () => ({
      ...(filter ? { filter } : {}),
      offset,
      limit,
    }),
    [filter, offset, limit],
  );
  const { items, total, isLoading, error, refetch } = useCollection(collectionKey, params);

  // Reset accumulated when filter changes (new section identity).
  useEffect(() => {
    setOffset(initialOffset);
    setAccumulated([]);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filterKey]);

  // Merge incoming items into accumulated. When offset is at the
  // section's starting offset, treat the response as the first page
  // (replace); otherwise append. Dedupe by slug to survive overlap.
  useEffect(() => {
    if (isLoading || error) return;
    if (offset === initialOffset) {
      setAccumulated(items);
    } else {
      setAccumulated((prev) => {
        const seen = new Set(prev.map((row) => row.slug));
        return [...prev, ...items.filter((row) => !seen.has(row.slug))];
      });
    }
  }, [items, isLoading, error, offset, initialOffset]);

  const canLoadMore = accumulated.length < total;
  const loadMore = () => setOffset((o) => o + limit);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 8, marginBottom: 16 }}>
      {showHeader ? (
        <div style={sectionHeaderStyle}>
          <span style={sectionLabelStyle}>{filterSummary(filter)}</span>
          <span style={sectionCountStyle}>
            {accumulated.length} / {total}
          </span>
        </div>
      ) : null}

      {error ? (
        <div style={errorStyle}>Liste alınamadı: {error.message}</div>
      ) : isLoading && accumulated.length === 0 ? (
        <div style={emptyStateStyle}>Yükleniyor…</div>
      ) : accumulated.length === 0 ? (
        <div style={emptyStateStyle}>Bu filtre için kayıt yok.</div>
      ) : (
        <ul style={listStyle} data-cms-list>
          {accumulated.map((item) => (
            <li key={item.id || item.slug} style={{ listStyle: "none" }}>
              <RegionItemCard
                collectionKey={collectionKey}
                slug={item.slug}
                canEdit={item.canEdit}
              />
            </li>
          ))}
        </ul>
      )}

      {canLoadMore ? (
        <button
          type="button"
          onClick={loadMore}
          disabled={isLoading}
          style={loadMoreStyle}
        >
          {isLoading ? "Yükleniyor…" : `Daha fazla yükle (${total - accumulated.length} kalan)`}
        </button>
      ) : null}

      {/* Subtle hint when manual refetch is useful (rare; mostly debug). */}
      {error ? (
        <button type="button" onClick={refetch} style={retryStyle}>Yeniden dene</button>
      ) : null}
    </div>
  );
}

/**
 * @param {{ collectionKey: string, slug: string, canEdit: boolean }} props
 */
function RegionItemCard({ collectionKey, slug, canEdit }) {
  const [isOpen, setIsOpen] = useState(false);
  const cardStyle = {
    ...blockCardStyle,
    border: isOpen ? COLLECTION_CARD_ACTIVE_BORDER : COLLECTION_CARD_BORDER,
  };

  return (
    <div style={cardStyle}>
      <button
        type="button"
        onClick={() => setIsOpen((v) => !v)}
        style={{
          ...blockHeaderStyle,
          background: "transparent",
          border: "none",
          width: "100%",
          textAlign: "left",
          cursor: "pointer",
          userSelect: "none",
          fontFamily: "inherit",
        }}
      >
        <span style={slugStyle}>{slug}</span>
        {!canEdit ? <span style={readonlyChipStyle}>readonly</span> : null}
        <motion.span
          initial={false}
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
          style={{ display: "inline-flex", color: TEXT_MUTED, marginLeft: "auto" }}
        >
          <ChevronDown size={14} />
        </motion.span>
      </button>

      <div style={{ display: isOpen ? "block" : "none" }}>
        <div style={blockBodyStyle}>
          <AdminCollectionEditor
            collection={collectionKey}
            slug={slug}
            showMetaRow={false}
          />
        </div>
      </div>
    </div>
  );
}

/**
 * @param {{ collectionKey: string, schema: import("../lib/schemas.js").CollectionSchema }} props
 */
function CreateForm({ collectionKey, schema }) {
  const { config, getAccessToken, updateCollectionItem } = useCmsContext();
  const [isOpen, setIsOpen] = useState(false);
  const [values, setValues] = useState(() => seedValues(schema.fields, {}));
  const [error, setError] = useState(/** @type {string | null} */ (null));
  const [isPending, startTransition] = useTransition();

  const reset = () => {
    setValues(seedValues(schema.fields, {}));
    setError(null);
  };

  const submit = () => {
    setError(null);
    const missing = requiredMissing(schema.fields, values);
    if (missing) {
      setError(`Zorunlu alan eksik: ${missing}`);
      return;
    }
    startTransition(async () => {
      try {
        const token = await getAccessToken();
        const init = token ? { headers: { Authorization: `Bearer ${token}` } } : undefined;
        const created = await createCollectionItem(
          config,
          collectionKey,
          { data: buildPayload(schema.fields, values) },
          init,
        );
        // updateCollectionItem invalidates every cached list window for
        // this collection - filtered sub-sections refetch on next
        // render and pick up (or correctly skip) the new row.
        updateCollectionItem(collectionKey, created.slug, created);
        reset();
        setIsOpen(false);
      } catch (err) {
        if (err instanceof CmsApiError && err.isForbidden) {
          setError("Bu collection'da kayıt oluşturma yetkin yok.");
        } else if (err instanceof CmsApiError && err.status === 400) {
          setError(`Geçersiz veri: ${err.detail || err.message}`);
        } else {
          setError(/** @type {Error} */ (err).message);
        }
      }
    });
  };

  return (
    <div style={createCardStyle}>
      <button
        type="button"
        onClick={() => setIsOpen((v) => !v)}
        style={createToggleStyle}
      >
        <Plus size={14} />
        <span>Yeni {collectionKey.toLowerCase()} ekle</span>
        <motion.span
          initial={false}
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.2 }}
          style={{ display: "inline-flex", color: TEXT_MUTED, marginLeft: "auto" }}
        >
          <ChevronDown size={13} />
        </motion.span>
      </button>

      <div style={{ display: isOpen ? "block" : "none" }}>
        <div style={{ padding: "10px 14px 14px", display: "flex", flexDirection: "column", gap: 10 }}>
          <CollectionFieldsForm
            fields={schema.fields}
            values={values}
            onChange={setValues}
            disabled={isPending}
          />
          {error ? <div style={errorStyle}>{error}</div> : null}
          <div style={{ display: "flex", gap: 8 }}>
            <button
              type="button"
              onClick={submit}
              disabled={isPending}
              style={primaryButtonStyle}
            >
              {isPending ? "Oluşturuluyor…" : "Oluştur"}
            </button>
            <button
              type="button"
              onClick={() => { setIsOpen(false); reset(); }}
              disabled={isPending}
              style={secondaryButtonStyle}
            >
              İptal
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

/** @param {Record<string, *> | undefined} filter */
function filterSummary(filter) {
  if (!filter || Object.keys(filter).length === 0) return "Filtresiz";
  return Object.entries(filter)
    .map(([k, v]) => `${k}=${String(v)}`)
    .join(" · ");
}

// ---- Styles --------------------------------------------------------------

const slugStyle = /** @type {React.CSSProperties} */ ({
  fontFamily: "ui-monospace, 'SF Mono', monospace",
  fontSize: 12,
  color: "rgba(255,255,255,0.85)",
  letterSpacing: "0.02em",
});

const readonlyChipStyle = /** @type {React.CSSProperties} */ ({
  color: TEXT_MUTED,
  textTransform: "uppercase",
  fontSize: 9,
  padding: "1px 6px",
  background: "rgba(255,255,255,0.05)",
  borderRadius: 3,
  letterSpacing: "0.05em",
  marginLeft: 8,
});

const sectionHeaderStyle = /** @type {React.CSSProperties} */ ({
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "8px 0 4px",
  fontSize: 11,
  fontFamily: "ui-monospace, 'SF Mono', monospace",
  letterSpacing: "0.04em",
  color: TEXT_MUTED,
  borderBottom: "1px dashed rgba(255,255,255,0.08)",
});

const sectionLabelStyle = /** @type {React.CSSProperties} */ ({
  color: "rgb(190, 180, 230)",
  textTransform: "uppercase",
});

const sectionCountStyle = /** @type {React.CSSProperties} */ ({
  marginLeft: "auto",
});

const errorStyle = /** @type {React.CSSProperties} */ ({
  color: "#ff8b8b",
  fontSize: 12,
  padding: "6px 10px",
  background: "rgba(226,100,100,0.10)",
  border: "1px solid rgba(226,100,100,0.30)",
  borderRadius: 3,
});

const loadMoreStyle = /** @type {React.CSSProperties} */ ({
  alignSelf: "center",
  padding: "6px 14px",
  background: "transparent",
  color: TEXT_MUTED,
  border: "1px solid rgba(255,255,255,0.15)",
  borderRadius: 3,
  cursor: "pointer",
  fontSize: 12,
  fontFamily: "inherit",
});

const retryStyle = /** @type {React.CSSProperties} */ ({
  alignSelf: "flex-start",
  padding: "4px 10px",
  background: "transparent",
  color: TEXT_MUTED,
  border: "1px solid rgba(255,255,255,0.15)",
  borderRadius: 3,
  cursor: "pointer",
  fontSize: 11,
});

const createCardStyle = /** @type {React.CSSProperties} */ ({
  border: "1px dashed rgba(140, 130, 210, 0.35)",
  borderRadius: 6,
  background: "rgba(140, 130, 210, 0.04)",
  marginBottom: 12,
  overflow: "hidden",
});

const createToggleStyle = /** @type {React.CSSProperties} */ ({
  width: "100%",
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "10px 14px",
  background: "transparent",
  border: "none",
  cursor: "pointer",
  color: "rgb(190, 180, 230)",
  fontSize: 12,
  fontWeight: 500,
  fontFamily: "inherit",
  letterSpacing: "0.02em",
});

const primaryButtonStyle = /** @type {React.CSSProperties} */ ({
  padding: "6px 14px",
  background: ACCENT,
  color: "#221d18",
  border: "none",
  borderRadius: 3,
  cursor: "pointer",
  fontSize: 12,
  fontWeight: 600,
  fontFamily: "inherit",
});

const secondaryButtonStyle = /** @type {React.CSSProperties} */ ({
  padding: "6px 14px",
  background: "transparent",
  color: TEXT_MUTED,
  border: "1px solid rgba(255,255,255,0.15)",
  borderRadius: 3,
  cursor: "pointer",
  fontSize: 12,
  fontFamily: "inherit",
});
