"use client";

/**
 * @file `CollectionComposer`: a plain "add one item" form for a single
 * collection, mounted by the host on its own page. Deliberately chrome-free:
 * no panel, no background, no CMS voice; it inherits the page's font and
 * colors so the screen reads "yeni haber ekle", not "CMS admin". The schema
 * comes from `/me`, in-progress values autosave into the backend's new-item
 * draft slot (so a refresh resumes where the editor left off), and submit
 * POSTs the row.
 *
 * Renders nothing for visitors without create access (`unauthorized`
 * overrides), so the page stays clean for everyone else.
 */

import { useState } from "react";

import { useCmsContext } from "../lib/context.js";
import { useMyCollections } from "../hooks/use-my-collections.js";
import { useCollectionCreate } from "../hooks/use-collection-create.js";
import { CollectionFieldsForm } from "./editors/CollectionFieldsForm.jsx";

/**
 * @param {Object} props
 * @param {string} props.collection     Backend collection key, e.g. "news".
 *   Must be creatable (`canCreate` + AutoGenerated slug); otherwise the
 *   composer renders nothing and warns in dev.
 * @param {(item: import("../lib/schemas.js").CollectionItemResponse) => void} [props.onCreated]
 *   Called after a successful create (e.g. redirect to the new item). Without
 *   it the form resets and shows a brief inline confirmation.
 * @param {string} [props.submitLabel]  Submit button text. Default "Oluştur".
 * @param {React.ReactNode} [props.unauthorized]  Shown to visitors without
 *   create access instead of nothing.
 * @param {string} [props.className]
 * @param {React.CSSProperties} [props.style]
 */
export function CollectionComposer({
  collection,
  onCreated,
  submitLabel = "Oluştur",
  unauthorized = null,
  className,
  style,
}) {
  const { isAdmin } = useCmsContext();
  const { collections: my, isLoading: meLoading } = useMyCollections();

  const meta = my.find((c) => c.collectionKey === collection) ?? null;
  const supportsCreate = Boolean(meta?.canCreate) && meta?.slugSource === "AutoGenerated";

  if (meLoading) return null;
  // Public visitor: nothing to create here, no warning (this is the normal
  // path for everyone not signed in).
  if (!isAdmin) return unauthorized ? <>{unauthorized}</> : null;
  // Admin, but the key isn't among this session's accessible collections.
  // Almost always a wrong/misspelled key or a missing membership; warn loudly
  // in dev so it isn't a silent blank (the trap: a typo'd key renders nothing).
  if (!meta) {
    if (process.env.NODE_ENV !== "production") {
      // eslint-disable-next-line no-console
      console.warn(
        `[inscribed] <CollectionComposer collection="${collection}">: not in this session's accessible collections (GET /cms/collections/me). Check the key's exact spelling/casing and that the membership grants access.`,
      );
    }
    return unauthorized ? <>{unauthorized}</> : null;
  }
  if (!supportsCreate || !meta.schema) {
    // Host misconfiguration, not an access issue: warn the developer, show
    // nobody anything.
    if (process.env.NODE_ENV !== "production") {
      // eslint-disable-next-line no-console
      console.warn(
        `[inscribed] <CollectionComposer collection="${collection}">: this collection isn't creatable (canCreate=${String(meta.canCreate)}, slugSource=${meta.slugSource}).`,
      );
    }
    return null;
  }

  return (
    <ComposerForm
      key={collection}
      collectionKey={collection}
      schema={meta.schema}
      onCreated={onCreated}
      submitLabel={submitLabel}
      className={className}
      style={style}
    />
  );
}

/**
 * Inner form, mounted only when create is allowed so `useCollectionCreate`
 * (and its sentinel list fetch) never runs for plain visitors.
 *
 * @param {{
 *   collectionKey: string,
 *   schema: import("../lib/schemas.js").CollectionSchema,
 *   onCreated?: (item: import("../lib/schemas.js").CollectionItemResponse) => void,
 *   submitLabel: string,
 *   className?: string,
 *   style?: React.CSSProperties,
 * }} props
 */
function ComposerForm({ collectionKey, schema, onCreated, submitLabel, className, style }) {
  const [justCreated, setJustCreated] = useState(false);
  const {
    values,
    setValues,
    submit,
    reset,
    deleteDraft,
    hasServerDraft,
    isPending,
    error,
  } = useCollectionCreate({ collectionKey, schema });

  const handleSubmit = () => {
    submit((item) => {
      if (onCreated) onCreated(item);
      else setJustCreated(true);
    });
  };

  return (
    <div
      className={`inscribed-composer${className ? ` ${className}` : ""}`}
      style={{ ...rootStyle, ...style }}
    >
      <style>{composerCss}</style>

      <CollectionFieldsForm
        fields={schema.fields}
        values={values}
        onChange={(next) => {
          setJustCreated(false);
          setValues(next);
        }}
        disabled={isPending}
      />

      {error ? <div style={errorStyle} role="alert">{error}</div> : null}
      {justCreated ? <div style={successStyle} role="status">Kaydedildi.</div> : null}

      <div style={actionsRowStyle}>
        {hasServerDraft ? (
          <button
            type="button"
            onClick={() => { reset(); deleteDraft(); }}
            disabled={isPending}
            className="inscribed-composer-ghost"
            style={ghostButtonStyle}
          >
            Temizle
          </button>
        ) : null}
        <button
          type="button"
          onClick={handleSubmit}
          disabled={isPending}
          className="inscribed-composer-submit"
          style={submitButtonStyle}
        >
          {isPending ? "Kaydediliyor…" : submitLabel}
        </button>
      </div>
    </div>
  );
}

// ---- Styles ----------------------------------------------------------------
//
// Same portability rule as CollectionFieldsForm: mid-gray alphas + inherit
// only, so the form sits on any host background without a theme.

const rootStyle = /** @type {React.CSSProperties} */ ({
  display: "flex",
  flexDirection: "column",
  gap: 16,
  color: "inherit",
  font: "inherit",
});

const actionsRowStyle = /** @type {React.CSSProperties} */ ({
  display: "flex",
  alignItems: "center",
  justifyContent: "flex-end",
  gap: 8,
});

const buttonBase = /** @type {React.CSSProperties} */ ({
  display: "inline-flex",
  alignItems: "center",
  gap: 6,
  padding: "8px 16px",
  borderRadius: 7,
  fontSize: 13,
  fontWeight: 500,
  fontFamily: "inherit",
  cursor: "pointer",
});

const submitButtonStyle = /** @type {React.CSSProperties} */ ({
  ...buttonBase,
  border: "1px solid rgba(127,127,127,0.35)",
  background: "rgba(127,127,127,0.10)",
  color: "inherit",
});

const ghostButtonStyle = /** @type {React.CSSProperties} */ ({
  ...buttonBase,
  border: "1px solid transparent",
  background: "transparent",
  color: "inherit",
  opacity: 0.6,
});

const errorStyle = /** @type {React.CSSProperties} */ ({
  padding: "9px 12px",
  fontSize: 13,
  lineHeight: 1.5,
  color: "inherit",
  background: "rgba(220, 60, 80, 0.08)",
  border: "1px solid rgba(220, 60, 80, 0.35)",
  borderRadius: 7,
});

const successStyle = /** @type {React.CSSProperties} */ ({
  padding: "9px 12px",
  fontSize: 13,
  lineHeight: 1.5,
  color: "inherit",
  background: "rgba(80, 180, 110, 0.10)",
  border: "1px solid rgba(80, 180, 110, 0.35)",
  borderRadius: 7,
});

// Neutral hover/focus: the shared admin CSS isn't on composer-only pages, and
// its white-alpha focus ring would vanish on light hosts anyway. Two-class
// specificity so these win when the drawer's stylesheet is also present.
const composerCss = `
  .inscribed-composer .inscribed-field {
    transition: border-color 140ms ease, background-color 140ms ease;
  }
  .inscribed-composer .inscribed-field:focus {
    border-color: rgba(127,127,127,0.55);
    background: rgba(127,127,127,0.08);
  }
  .inscribed-composer .inscribed-composer-submit {
    transition: background 140ms ease, border-color 140ms ease;
  }
  .inscribed-composer .inscribed-composer-submit:hover:not(:disabled) {
    background: rgba(127,127,127,0.16);
    border-color: rgba(127,127,127,0.5);
  }
  .inscribed-composer .inscribed-composer-submit:disabled,
  .inscribed-composer .inscribed-composer-ghost:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .inscribed-composer .inscribed-composer-ghost { transition: opacity 140ms ease; }
  .inscribed-composer .inscribed-composer-ghost:hover:not(:disabled) { opacity: 1; }
`;
