// @vitest-environment jsdom
/**
 * Archiving, restoring, and the 409 that means "taken down" rather than
 * "someone got there first".
 *
 * The two are deliberately not symmetric on the wire: archiving proves the
 * caller saw the current content by sending its version, restoring sends none,
 * because archiving does not consume one. The same number that archived a row
 * still publishes it afterwards, which the version assertions here pin down.
 */
import { describe, it, expect, afterEach, beforeEach, vi } from "vitest";
import React from "react";
import { render, cleanup, act, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/haberler",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { useCollectionEditor } from "../../collections/hooks/use-collection-editor.js";
import { CmsApiError } from "../../shared/contracts/errors.js";
import { en } from "../../shared/i18n/en/index.js";

const COLLECTION = "news";
const SLUG = "eski-haber";

const SCHEMA = {
  fields: [{
    name: "title",
    label: "Başlık",
    type: "ShortText",
    required: false,
    readOnly: false,
    computed: false,
    filterable: false,
    sortable: false,
    options: null,
    itemFields: null,
    help: null,
  }],
};

let server;
let calls;

const probe = /** @type {{ editor: * }} */ ({});

function Harness() {
  probe.editor = useCollectionEditor(COLLECTION, SLUG);
  return null;
}

async function settle() {
  await act(async () => {});
}

const row = () => (server.virtual ? {
  collectionKey: COLLECTION,
  origin: "derived",
  slug: SLUG,
  canEdit: true,
  data: {},
} : {
  id: "row-1",
  collectionKey: COLLECTION,
  slug: SLUG,
  data: { title: "Eski haber" },
  version: server.version,
  canEdit: true,
  // Absent rather than false while live: the backend sends the flag only on an
  // archived row, and the editor has to read absence as "not archived".
  ...(server.archived ? { isArchived: true, archivedAt: "2026-08-11T06:06:46Z" } : null),
});

const transport = {
  getContent: async () => ({ slug: "/haberler", blocks: [] }),
  getMyCollections: async () => [{
    collectionKey: COLLECTION,
    canCreate: true,
    slugSource: "AutoGenerated",
    schema: SCHEMA,
  }],
  getCollectionItem: async () => row(),
  getCollection: async () => ({ items: [row()], total: 1, offset: 0, limit: 50 }),
  archiveCollectionItem: async (key, slug, version) => {
    calls.push(`archive:v${version}`);
    if (server.archived) {
      throw new CmsApiError({
        status: 409, detail: "already archived", reason: "archived",
      });
    }
    if (version !== server.version) {
      throw new CmsApiError({ status: 409, detail: `Expected ${server.version}` });
    }
    server.archived = true;
    return { collectionKey: key, slug, version };
  },
  restoreCollectionItem: async () => {
    calls.push("restore");
    server.archived = false;
    return row();
  },
  upsertCollectionItem: async () => {
    calls.push("upsert");
    if (server.archived) {
      throw new CmsApiError({
        status: 409,
        detail: "Item is archived; restore it before writing to it.",
        reason: "archived",
      });
    }
    server.version += 1;
    return row();
  },
  saveCollectionItemDraft: async () => {},
  deleteCollectionItemDraft: async () => {},
};

async function mount() {
  await act(async () => {
    render(
      <CmsProvider collections={CollectionProvider}
        config={{ baseUrl: "https://api.test" }}
        transport={/** @type {*} */ (transport)}
        isAdmin
      >
        <Harness />
      </CmsProvider>,
    );
  });
  await settle();
}

beforeEach(() => {
  server = { version: 3, archived: false, virtual: false };
  calls = [];
});

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("archiving", () => {
  it("sends the row's current version and flips isArchived", async () => {
    await mount();
    expect(probe.editor.isArchived).toBe(false);

    act(() => { probe.editor.archive(); });
    await waitFor(() => expect(probe.editor.isArchived).toBe(true));
    expect(calls).toEqual(["archive:v3"]);
  });

  it("does not consume the version, so the same number restores and publishes", async () => {
    await mount();

    act(() => { probe.editor.archive(); });
    await waitFor(() => expect(probe.editor.isArchived).toBe(true));
    expect(probe.editor.item.version).toBe(3);

    act(() => { probe.editor.restore(); });
    await waitFor(() => expect(probe.editor.isArchived).toBe(false));
    expect(probe.editor.item.version).toBe(3);
  });

  it("is a no-op on a claim-derived row that was never saved", async () => {
    // A virtual body carries neither id nor version, so there is nothing to
    // take down and nothing to prove the caller saw.
    server.virtual = true;
    await mount();
    expect(probe.editor.isVirtual).toBe(true);

    act(() => { probe.editor.archive(); });
    await settle();
    expect(calls).toEqual([]);
  });

  it("is a no-op on a row that is already archived", async () => {
    server.archived = true;
    await mount();

    act(() => { probe.editor.archive(); });
    await settle();
    expect(calls).toEqual([]);
  });
});

describe("writing to an archived row", () => {
  it("reports it as archived rather than as a version conflict", async () => {
    server.archived = true;
    await mount();

    act(() => { probe.editor.setValues({ title: "Yeni" }); });
    act(() => { probe.editor.save(); });

    await waitFor(() => expect(probe.editor.error).toBe(en["collections.archivedConflict"]));
    expect(probe.editor.error).not.toBe(en["collections.versionConflict"]);
  });

  it("clears once the row is restored", async () => {
    server.archived = true;
    await mount();
    expect(probe.editor.isArchived).toBe(true);

    act(() => { probe.editor.restore(); });
    await waitFor(() => expect(probe.editor.isArchived).toBe(false));

    act(() => { probe.editor.setValues({ title: "Yeni" }); });
    act(() => { probe.editor.save(); });
    await waitFor(() => expect(calls).toContain("upsert"));
    expect(probe.editor.error).toBe(null);
  });
});

describe("CmsApiError", () => {
  it("separates an archived conflict from a plain one", () => {
    const archived = new CmsApiError({ status: 409, detail: "x", reason: "archived" });
    const race = new CmsApiError({ status: 409, detail: "x" });

    expect(archived.isConflict).toBe(true);
    expect(archived.isArchivedConflict).toBe(true);
    expect(race.isConflict).toBe(true);
    expect(race.isArchivedConflict).toBe(false);
  });
});
