// @vitest-environment jsdom
/**
 * @file What the collections landing says about a collection before you open it.
 *
 * It described the shape of a record (which fields, how many, which languages)
 * and never said how many records there were, which is the first thing anyone
 * wants to know. `/me` carries no count, so the number comes from the list
 * endpoint's `total`: one request per collection, which is what this screen's
 * handful of rows costs.
 *
 * The number is a figure with its unit under it, opposite a key set at
 * headline size. Those two go together: the figure alone, against a key still
 * sitting at 11px among the metadata, was simply the loudest thing on the
 * screen. What holds it in place is the other side of the row.
 *
 * The headline is the collection's `displayName` where it has one and its key
 * where it does not, and the two are set differently on purpose: a name is
 * prose, a key is a literal.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { CollectionsPane } from "../../admin/CollectionsPane.jsx";
import { createCmsConfig } from "../../shared/config.js";

const CONFIG = createCmsConfig({ baseUrl: "https://api.test" });
const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const field = (name) => ({
  name, type: "ShortText", label: name, required: false, readOnly: false,
  computed: false, options: null, itemFields: null, help: null,
});

const meta = (collectionKey, extra = {}) => ({
  collectionKey,
  canCreate: true,
  slugSource: "AutoGenerated",
  displayField: "name",
  schema: { fields: [field("name"), field("body")] },
  ...extra,
});

/** Requests captured as urls, so the cost of the counts is assertable. */
let requests;

/** @param {Record<string, number|"fail">} totals  Per collection key. */
function mockFetch(totals, names = {}) {
  requests = [];
  global.fetch = vi.fn(async (input) => {
    const url = String(input);
    requests.push(url);
    if (url.includes("/cms/collections/me")) {
      return jsonRes(Object.keys(totals).map((k) => meta(k, names[k] ? { displayName: names[k] } : {})));
    }
    for (const [key, total] of Object.entries(totals)) {
      if (url.includes(`/cms/collections/${key}`)) {
        if (total === "fail") return jsonRes({ message: "boom" }, 500);
        return jsonRes({ items: [], total, offset: 0, limit: 1, virtualItems: [] });
      }
    }
    return jsonRes({ slug: "/", blocks: [] });
  });
}

function renderPane(totals, names) {
  mockFetch(totals, names);
  return render(
    <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
      <CollectionsPane onSelect={() => {}} />
    </CmsProvider>,
  );
}

/** The row button carrying this collection key. */
const rowFor = (key) => screen.getByText(key).closest("button");

const listRequests = (key) => requests.filter(
  (u) => u.includes(`/cms/collections/${key}`) && !u.includes("/me"),
);

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("the record count", () => {
  it("says how many records each collection holds", async () => {
    renderPane({ news: 12, events: 48 });

    await waitFor(() => expect(rowFor("news")?.textContent).toContain("12"));
    expect(rowFor("events")?.textContent).toContain("48");
  });

  // A zero that becomes forty-eight is worse than a beat of nothing: a wrong
  // number is one somebody may act on.
  it("shows nothing rather than a placeholder number while it loads", async () => {
    renderPane({ news: 12 });
    // Before the list lands, the row is already there and carries no count.
    expect(screen.queryByText("0")).toBeNull();
    await waitFor(() => expect(rowFor("news")?.textContent).toContain("12"));
  });

  // An empty collection is a real answer, and the one most worth seeing.
  it("says zero when a collection really holds nothing", async () => {
    renderPane({ news: 0 });
    await waitFor(() => expect(rowFor("news")?.textContent).toContain("0"));
  });

  // The count is the one thing on this row that can fail on its own. Losing it
  // must not take the row with it.
  it("keeps the row when the count cannot be fetched", async () => {
    renderPane({ news: "fail" });
    await waitFor(() => expect(rowFor("news")).toBeTruthy());
    expect(rowFor("news")?.textContent).toContain("news");
  });

  // One row of payload is enough to be told the total, and it is the least the
  // endpoint will answer with.
  it("asks for one row, not the whole collection", async () => {
    renderPane({ news: 12 });
    await waitFor(() => expect(rowFor("news")?.textContent).toContain("12"));

    const [url] = listRequests("news");
    expect(new URL(url).searchParams.get("limit")).toBe("1");
  });

  it("asks once per collection, not once per render", async () => {
    renderPane({ news: 12, events: 48 });
    await waitFor(() => expect(rowFor("events")?.textContent).toContain("48"));

    expect(listRequests("news").length).toBe(1);
    expect(listRequests("events").length).toBe(1);
  });
});

describe("how the count is drawn", () => {
  // A lone integer at the edge of a row could be counting anything; the unit is
  // what makes it records rather than the field count on the line below.
  it("carries its unit, so the figure means something", async () => {
    renderPane({ news: 12 });
    await waitFor(() => expect(rowFor("news")?.textContent).toContain("12"));

    const el = rowFor("news")?.querySelector('[title*="12"]');
    expect(el?.textContent).toContain("12");
    expect(el?.textContent?.toLowerCase()).toContain("records");
  });

  // Tabular figures, so the numbers form a column to compare down rather than a
  // ragged edge.
  it("lines its digits up down the list", async () => {
    renderPane({ news: 12, events: 4, staff: 102 });
    await waitFor(() => expect(rowFor("staff")?.textContent).toContain("102"));

    const figure = rowFor("staff")?.querySelector('[title*="102"] span');
    expect(figure?.style.fontVariantNumeric).toBe("tabular-nums");
  });
});

/** The base px of a `calc(Npx * var(--ins-font-scale))` size. */
const basePx = (el) => Number(/([\d.]+)px/.exec(el?.style.fontSize ?? "")?.[1]);

describe("the row's headline", () => {
  // The count only reads as the row's anchor if the other side holds the line.
  it("sets it at a heading's size, above the properties", async () => {
    renderPane({ news: 12 });
    await waitFor(() => expect(rowFor("news")).toBeTruthy());

    const headline = screen.getByText("news");
    const properties = headline.parentElement?.nextElementSibling;
    expect(basePx(headline)).toBeGreaterThan(12);
    expect(basePx(headline)).toBeGreaterThan(basePx(properties));
  });

  it("uses the collection's own name when it has one", async () => {
    renderPane({ news: 12 }, { news: "Haberler" });
    await waitFor(() => expect(screen.getByText("Haberler")).toBeTruthy());

    // The key is still there, demoted to the address on the line below.
    const row = screen.getByText("Haberler").closest("button");
    expect(row?.textContent).toContain("news");
  });

  // The fallback headline (no displayName) still reads as a heading, not as a
  // literal identifier set apart in mono.
  it("sets both a name and a fallback key in the sans", async () => {
    renderPane({ news: 12 }, { news: "Haberler" });
    await waitFor(() => expect(screen.getByText("Haberler")).toBeTruthy());
    expect(screen.getByText("Haberler").style.fontFamily).not.toContain("mono");

    cleanup();
    renderPane({ events: 4 });
    await waitFor(() => expect(screen.getByText("events")).toBeTruthy());
    expect(screen.getByText("events").style.fontFamily).not.toContain("mono");
  });

  // Said once, in the row, rather than left to a tint the reader has to know.
  it("says the page binding in words", async () => {
    renderPane({ news: 12 });
    await waitFor(() => expect(rowFor("news")).toBeTruthy());
    // Nothing binds this page in the test, so the badge stays away.
    expect(screen.queryByText("On this page")).toBeNull();
  });
});
