// @vitest-environment jsdom
/**
 * Tests for `useCollectionLocale`: which language a collection request is
 * addressed in. The site's locale list and the collection's are different
 * lists, and a write naming a language the collection never declared is
 * rejected, so `/me` decides rather than the route.
 *
 * Driven through `<CollectionComposer>` because it exercises both halves at
 * once: the list read that finds the pending draft row, and the create POST.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, fireEvent, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
// Under `/tr` on a site serving Turkish and English, so the route has a locale
// to offer every collection below.
vi.mock("next/navigation", () => ({
  usePathname: () => "/tr",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionComposer } from "../../collections/CollectionComposer.jsx";
import { useCollection } from "../../collections/hooks/use-collection.js";
import { createCmsConfig } from "../../shared/config.js";
import { en } from "../../shared/i18n/en/index.js";

const BASE = "https://api.test";
const CONFIG = createCmsConfig({ baseUrl: BASE, locales: ["tr", "en"] });

const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const newsMeta = (locales) => ({
  collectionKey: "news",
  canCreate: true,
  slugSource: "AutoGenerated",
  locales,
  schema: {
    fields: [
      { name: "title", label: "Başlık", type: "ShortText", required: true, readOnly: false, options: null, fields: null, help: null },
    ],
  },
});

/** Every request as [method, URL], so a locale can be read off any of them. */
let requests;

/**
 * @param {{ locales?: string[], me?: Promise<void> }} options
 *   `me` gates the /me response, for the "waits before asking" case.
 */
function mockFetch({ locales, me } = {}) {
  requests = [];
  global.fetch = vi.fn(async (input, init) => {
    const url = String(input);
    const method = init?.method ?? "GET";
    requests.push([method, url]);
    if (url.includes("/cms/collections/me")) {
      if (me) await me;
      return jsonRes([newsMeta(locales)]);
    }
    if (url.includes("/cms/collections/news") && method === "POST" && !url.includes("/drafts")) {
      return jsonRes({
        id: "row-1",
        collectionKey: "news",
        slug: "yeni-haber",
        data: JSON.parse(String(init.body)).data,
        version: 1,
        canEdit: true,
      });
    }
    if (url.includes("/cms/collections/news")) {
      return jsonRes({ items: [], total: 0, offset: 0, limit: 50, virtualItems: [] });
    }
    return jsonRes({ slug: "/", blocks: [] });
  });
}

function renderComposer() {
  return renderInProvider(<CollectionComposer collection="news" />);
}

function renderInProvider(children) {
  return render(
    <CmsProvider config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
      {children}
    </CmsProvider>,
  );
}

/** Reads a window straight away, unlike the composer, which waits for /me. */
function Rows() {
  const { items } = useCollection("news");
  return <div data-testid="rows">{items.length}</div>;
}

/** The locale of the first request matching `method` + `test`, or undefined. */
function localeOf(method, test) {
  const hit = requests.find(([m, url]) => m === method && test(url));
  return hit ? new URL(hit[1]).searchParams.get("locale") : undefined;
}

const listLocale = () => localeOf("GET", (url) => url.includes("/cms/collections/news"));
const createLocale = () =>
  localeOf("POST", (url) => url.includes("/cms/collections/news") && !url.includes("/drafts"));

/** Fill the one required field and publish. */
async function submit() {
  await waitFor(() => expect(screen.getByText(en["collections.create"])).toBeTruthy());
  const [titleInput] = Array.from(document.querySelectorAll("input.inscribed-field"));
  fireEvent.change(titleInput, { target: { value: "Merhaba" } });
  fireEvent.click(screen.getByText(en["collections.create"]));
  await waitFor(() => expect(createLocale()).not.toBeUndefined());
}

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("a collection that declares no locales", () => {
  it("is read without one, so every language of the site shares its window", async () => {
    mockFetch({ locales: [] });
    renderComposer();
    await waitFor(() => expect(listLocale()).not.toBeUndefined());
    expect(listLocale()).toBeNull();
  });

  it("is written without one, which is the half the backend rejects", async () => {
    mockFetch({ locales: [] });
    renderComposer();
    await submit();
    expect(createLocale()).toBeNull();
  });

  it("treats an absent locales field the same as an empty one", async () => {
    mockFetch({ locales: undefined });
    renderComposer();
    await waitFor(() => expect(listLocale()).not.toBeUndefined());
    expect(listLocale()).toBeNull();
  });
});

describe("a collection that declares the route's locale", () => {
  it("is read and written in it", async () => {
    mockFetch({ locales: ["tr", "en"] });
    renderComposer();
    await submit();
    expect(listLocale()).toBe("tr");
    expect(createLocale()).toBe("tr");
  });
});

describe("a collection localized in other languages", () => {
  it("falls back to its own default rather than sending a language it lacks", async () => {
    mockFetch({ locales: ["en", "de"] });
    renderComposer();
    await waitFor(() => expect(listLocale()).not.toBeUndefined());
    expect(listLocale()).toBeNull();
  });
});

describe("before /me arrives", () => {
  it("holds the list request rather than guessing the locale and refetching", async () => {
    let release = () => {};
    const gate = new Promise((resolve) => { release = resolve; });
    mockFetch({ locales: [], me: gate });
    renderInProvider(<Rows />);

    await waitFor(() =>
      expect(requests.some(([, url]) => url.includes("/cms/collections/me"))).toBe(true),
    );
    expect(requests.some(([m, url]) => m === "GET" && url.includes("/cms/collections/news"))).toBe(false);

    release();
    await waitFor(() => expect(listLocale()).not.toBeUndefined());
    expect(listLocale()).toBeNull();
    // One window, one request: a locale guessed early would have keyed a second.
    expect(requests.filter(([m, url]) => m === "GET" && url.includes("/cms/collections/news")))
      .toHaveLength(1);
  });
});
