// @vitest-environment jsdom
/**
 * @file The create row leaving and coming back as the archive is toggled.
 *
 * It used to be mounted behind a plain condition, so switching to the archive
 * dropped it instantly and snapped everything below up by its own height, while
 * the list underneath was still cross-fading. The row is in the flow, so what
 * has to be continuous is the height: a fade alone leaves the jump intact.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, fireEvent, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { CollectionRegionPanel } from "../../admin/CollectionRegionPanel.jsx";
import { createCmsConfig } from "../../shared/config.js";
import {
  CREATE_COLLAPSE_TRANSITION, createCollapseStyle,
} from "../../admin/collection/collection-styles.js";
import { en } from "../../shared/i18n/en/index.js";

const BASE = "https://api.test";
const KEY = "probe-news";
const CONFIG = createCmsConfig({ baseUrl: BASE });
const t = (key) => en[key] ?? key;

const jsonRes = (body) => new Response(JSON.stringify(body), { status: 200 });

const ITEM = {
  id: "row-1", collectionKey: KEY, slug: "alfa",
  data: { name: "Alfa" }, version: 1, canEdit: true,
};

function renderPanel() {
  global.fetch = vi.fn(async (input) => {
    const url = String(input);
    if (url.includes("/cms/collections/me")) {
      return jsonRes([{
        collectionKey: KEY,
        canCreate: true,
        slugSource: "AutoGenerated",
        schema: {
          fields: [{
            name: "name", type: "ShortText", label: "Ad", required: false,
            readOnly: false, computed: false, options: null, itemFields: null, help: null,
          }],
        },
      }]);
    }
    if (url.includes(`/cms/collections/${KEY}`)) {
      const archived = new URL(url).searchParams.get("archived") === "true";
      return jsonRes({
        items: archived ? [] : [ITEM],
        total: archived ? 0 : 1,
        offset: 0, limit: 50, virtualItems: [],
      });
    }
    return jsonRes({ slug: "/", blocks: [] });
  });

  return render(
    <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
      <CollectionRegionPanel collectionKey={KEY} scope="global" />
    </CmsProvider>,
  );
}

/** The wrapper the create row collapses inside, whether or not it holds one. */
const collapser = (container) =>
  [...container.querySelectorAll("div")].find((el) => el.style.overflow === "hidden");

const createRow = () => document.querySelector(".inscribed-create-row");
const archiveChip = () => screen.getByRole("button", { name: /archive/i });

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("the create row and the archive", () => {
  it("offers a new record on the live list", async () => {
    renderPanel();
    await waitFor(() => expect(createRow()).toBeTruthy());
  });

  // Nothing can be created in the archive: every write against an archived row
  // answers 409 until it is restored.
  it("takes the row away in the archive", async () => {
    renderPanel();
    await waitFor(() => expect(createRow()).toBeTruthy());

    fireEvent.click(archiveChip());
    await waitFor(() => expect(createRow()).toBeNull());
  });

  it("brings it back on the way out of the archive", async () => {
    renderPanel();
    await waitFor(() => expect(createRow()).toBeTruthy());

    fireEvent.click(archiveChip());
    await waitFor(() => expect(createRow()).toBeNull());

    fireEvent.click(archiveChip());
    await waitFor(() => expect(createRow()).toBeTruthy());
  });

  // The actual fix: the row lives inside a clipping wrapper whose height is
  // animated, rather than being mounted and unmounted on a bare condition.
  it("leaves through a height that clips rather than vanishing", async () => {
    const { container } = renderPanel();
    await waitFor(() => expect(createRow()).toBeTruthy());

    const el = collapser(container);
    expect(el).toBeTruthy();
    expect(el?.contains(createRow())).toBe(true);
  });
});

describe("the collapse's own values", () => {
  it("clips, so the height reduces the row instead of squashing it", () => {
    expect(createCollapseStyle.overflow).toBe("hidden");
  });

  // The drawer's group cards collapse on exactly these, and a panel that opens
  // and closes at two speeds is not something anyone should have to notice.
  it("runs at the drawer's own collapse speed", () => {
    expect(CREATE_COLLAPSE_TRANSITION.duration).toBe(0.24);
    expect(CREATE_COLLAPSE_TRANSITION.ease).toEqual([0.32, 0.72, 0.18, 1]);
  });
});
