// @vitest-environment jsdom
/**
 * Writing a record in a language other than the one on screen: the drawer's
 * "+ EN" on a Turkish record, and a composer pinned to English on a Turkish
 * page.
 *
 * Two things have to follow the language being written rather than the one
 * being read. The half-finished draft the form opens on lives in one slot per
 * language, and the translation group the new record joins has to reach
 * whichever create route the collection publishes through.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, fireEvent, waitFor, within } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { CollectionRegionPanel } from "../../admin/CollectionRegionPanel.jsx";
import { CollectionComposer } from "../../collections/CollectionComposer.jsx";
import { createCmsConfig } from "../../shared/config.js";
import { createTranslator, resolveStrings } from "../../shared/i18n/translate.js";

const t = createTranslator(resolveStrings("en"), "en");

const BASE = "https://api.test";
const KEY = "probe-news";
// The route is unprefixed, so the page on screen is the Turkish one.
const CONFIG = createCmsConfig({ baseUrl: BASE, locales: ["tr", "en"] });
const GROUP = "0f6c1d2e-5b7a-4c1e-9a3d-2b8e6f4a1c90";

const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const meta = (slugSource) => ({
  collectionKey: KEY,
  canCreate: true,
  slugSource,
  locales: ["tr", "en"],
  schema: {
    fields: [
      { name: "title", label: "Başlık", type: "ShortText", required: true, readOnly: false, computed: false, options: null, itemFields: null, help: null },
    ],
  },
});

const turkishRecord = {
  id: "row-tr",
  collectionKey: KEY,
  slug: "tanitim-gunu",
  locale: "tr",
  translationGroupId: GROUP,
  translations: [],
  data: { title: "Tanıtım günü" },
  version: 1,
  canEdit: true,
};

/** Each language's pending new-record draft, as that language's list reports it. */
const PENDING = {
  tr: { title: "Türkçe yarım kayıt" },
  en: { title: "English half-written" },
};

/** Every request as [method, url]. */
let requests;

/** @param {{ slugSource?: string, pending?: Record<string, object> }} [options] */
function mockFetch({ slugSource = "AutoGenerated", pending = PENDING } = {}) {
  requests = [];
  global.fetch = vi.fn(async (input, init) => {
    const url = String(input);
    const method = init?.method ?? "GET";
    requests.push([method, url]);
    const { pathname, searchParams } = new URL(url);
    if (pathname === "/cms/collections/me") return jsonRes([meta(slugSource)]);
    if (method === "PUT" && pathname === `/cms/collections/${KEY}/open-day`) {
      return jsonRes({ ...turkishRecord, id: "row-en", slug: "open-day", locale: "en", data: { title: "Open day" } });
    }
    if (method === "POST" && pathname === `/cms/collections/${KEY}`) {
      return jsonRes({ ...turkishRecord, id: "row-en", slug: "open-day", locale: "en", data: { title: "Open day" } });
    }
    if (method !== "GET") return new Response(null, { status: 204 });
    if (pathname === `/cms/collections/${KEY}/${turkishRecord.slug}`) return jsonRes(turkishRecord);
    if (pathname === `/cms/collections/${KEY}`) {
      const locale = searchParams.get("locale");
      const draft = pending[locale];
      return jsonRes({
        items: locale === "tr" ? [turkishRecord] : [],
        total: locale === "tr" ? 1 : 0,
        offset: 0,
        limit: 50,
        virtualItems: draft ? [{ origin: "pending", canEdit: true, data: {}, draftData: draft }] : [],
      });
    }
    return jsonRes({ slug: "/", blocks: [] });
  });
}

function renderPanel() {
  return render(
    <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
      <CollectionRegionPanel collectionKey={KEY} scope="global" />
    </CmsProvider>,
  );
}

/**
 * The schema's own input: the slug box wears the same class but is not one.
 *
 * @param {ParentNode} [root]
 */
const titleInput = (root = document) => /** @type {HTMLInputElement | undefined} */ (
  Array.from(root.querySelectorAll("input.inscribed-field"))
    .find((el) => /** @type {HTMLInputElement} */ (el).placeholder !== t("collections.slugPlaceholder"))
);

/**
 * Scoped, because the Turkish record's pane is still leaving while this one
 * arrives, and its title input is the same kind of field.
 */
const englishPane = () => screen.getByRole("region", { name: t("collections.newRecordInLocale", { key: KEY, locale: "EN" }) });

/** Open the Turkish record, then its "+ EN" create pane. */
async function openEnglishTranslation() {
  // No display field, so the row is headlined by its slug.
  await waitFor(() => expect(screen.getByText(turkishRecord.slug)).toBeTruthy());
  fireEvent.click(screen.getByText(turkishRecord.slug));
  fireEvent.click(await screen.findByTitle(t("collections.addTranslation", { locale: "EN" })));
  await waitFor(() => expect(titleInput(englishPane())).toBeTruthy());
}

const createRequest = (method, path) => requests.find(([m, url]) => m === method && new URL(url).pathname === path);

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("the draft a translation form opens on", () => {
  it("is the English one when the drawer's list is Turkish", async () => {
    mockFetch();
    renderPanel();
    await openEnglishTranslation();

    await waitFor(() => expect(titleInput(englishPane())?.value).toBe(PENDING.en.title));
  });

  it("is the English one when a composer is pinned to English on a Turkish page", async () => {
    mockFetch();
    render(
      <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
        <CollectionComposer collection={KEY} locale="en" />
      </CmsProvider>,
    );

    await waitFor(() => expect(titleInput()?.value).toBe(PENDING.en.title));
  });
});

describe("the group a translation joins", () => {
  it("reaches the POST when the backend derives the slug", async () => {
    mockFetch({ pending: {} });
    renderPanel();
    await openEnglishTranslation();
    fireEvent.change(titleInput(englishPane()), { target: { value: "Open day" } });
    fireEvent.click(within(englishPane()).getByText(t("collections.create")));

    await waitFor(() => expect(createRequest("POST", `/cms/collections/${KEY}`)).toBeTruthy());
    const [, url] = createRequest("POST", `/cms/collections/${KEY}`);
    expect(new URL(url).searchParams.get("translationGroup")).toBe(GROUP);
    expect(new URL(url).searchParams.get("locale")).toBe("en");
  });

  it("reaches the PUT when the editor types the slug", async () => {
    mockFetch({ slugSource: "UserDefined", pending: {} });
    renderPanel();
    await openEnglishTranslation();
    const pane = englishPane();
    fireEvent.change(within(pane).getByPlaceholderText(t("collections.slugPlaceholder")), { target: { value: "open-day" } });
    fireEvent.change(titleInput(pane), { target: { value: "Open day" } });
    fireEvent.click(within(pane).getByText(t("collections.create")));

    await waitFor(() => expect(createRequest("PUT", `/cms/collections/${KEY}/open-day`)).toBeTruthy());
    const [, url] = createRequest("PUT", `/cms/collections/${KEY}/open-day`);
    expect(new URL(url).searchParams.get("translationGroup")).toBe(GROUP);
    expect(new URL(url).searchParams.get("locale")).toBe("en");
  });
});
