// @vitest-environment jsdom
/**
 * One new record written in several languages at once, from the page's
 * composer and from the panel's create pane.
 *
 * Each language is its own row in the backend, so the claims under test are
 * about how they go out: one create per language, in order, every one after
 * the first joined to the first one's translation group; the fields that are
 * not prose written into all of them; and a language that fails left to retry
 * on its own, without the ones that landed being sent twice.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, fireEvent, waitFor, within } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { CollectionComposer } from "../../collections/CollectionComposer.jsx";
import { CollectionRegionPanel } from "../../admin/CollectionRegionPanel.jsx";
import { createCmsConfig } from "../../shared/config.js";
import { createTranslator, resolveStrings } from "../../shared/i18n/translate.js";

const t = createTranslator(resolveStrings("en"), "en");

const BASE = "https://api.test";
const KEY = "probe-news";
// Unprefixed route, so the page on screen is the Turkish one.
const CONFIG = createCmsConfig({ baseUrl: BASE, locales: ["tr", "en"] });

const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const meta = (slugSource) => ({
  collectionKey: KEY,
  canCreate: true,
  slugSource,
  locales: ["tr", "en"],
  schema: {
    fields: [
      { name: "title", label: "Başlık", type: "ShortText", required: true, readOnly: false, computed: false, options: null, itemFields: null, help: null },
      { name: "summary", label: "Özet", type: "LongText", required: false, readOnly: false, computed: false, options: null, itemFields: null, help: null },
      { name: "featured", label: "Öne çıkan", type: "Bool", required: false, readOnly: false, computed: false, options: null, itemFields: null, help: null },
    ],
  },
});

/** Every request as { method, url, body }. */
let requests;

/**
 * @param {{
 *   slugSource?: string,
 *   pending?: Record<string, object>,
 *   failOnce?: string,
 * }} [options]
 *   `failOnce` names a language whose first create answers 500.
 */
function mockFetch({ slugSource = "AutoGenerated", pending = {}, failOnce } = {}) {
  requests = [];
  let failed = false;
  global.fetch = vi.fn(async (input, init) => {
    const url = new URL(String(input));
    const method = init?.method ?? "GET";
    const body = init?.body ? JSON.parse(String(init.body)) : null;
    requests.push({ method, url, body });
    const locale = url.searchParams.get("locale");
    if (url.pathname === "/cms/collections/me") return jsonRes([meta(slugSource)]);

    const creates = (method === "POST" && url.pathname === `/cms/collections/${KEY}`)
      || (method === "PUT" && url.pathname.startsWith(`/cms/collections/${KEY}/`) && !url.pathname.endsWith("/draft"));
    if (creates) {
      if (locale === failOnce && !failed) {
        failed = true;
        return jsonRes({ title: "Server error", status: 500, detail: "boom" }, 500);
      }
      const slug = method === "PUT" ? url.pathname.split("/").pop() : `${locale}-kayit`;
      return jsonRes({
        id: `row-${locale}`,
        collectionKey: KEY,
        slug,
        locale,
        // A standalone record starts a group named after it; a translation
        // echoes the group it was sent.
        translationGroupId: url.searchParams.get("translationGroup") ?? `group-${locale}`,
        data: body.data,
        version: 1,
        canEdit: true,
      });
    }
    if (method !== "GET") return new Response(null, { status: 204 });
    if (url.pathname === `/cms/collections/${KEY}`) {
      const draft = pending[locale];
      return jsonRes({
        items: [],
        total: 0,
        offset: 0,
        limit: 50,
        virtualItems: draft ? [{ origin: "pending", canEdit: true, data: {}, draftData: draft }] : [],
      });
    }
    return jsonRes({ slug: "/", blocks: [] });
  });
}

/** The create requests in the order they went out. */
const creates = () => requests.filter(({ method, url }) =>
  (method === "POST" && url.pathname === `/cms/collections/${KEY}`)
  || (method === "PUT" && url.pathname.startsWith(`/cms/collections/${KEY}/`) && !url.pathname.endsWith("/draft")));

function renderComposer(props = {}) {
  return render(
    <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
      <CollectionComposer collection={KEY} {...props} />
    </CmsProvider>,
  );
}

const languageRow = () => screen.getByRole("group", { name: t("collections.languages") });

async function addEnglish() {
  fireEvent.click(await screen.findByLabelText(t("collections.addLanguage", { locale: "EN" })));
  await waitFor(() => expect(screen.getByLabelText("Başlık EN")).toBeTruthy());
}

/** @param {HTMLElement} input @param {string} value */
const type = (input, value) => fireEvent.change(input, { target: { value } });

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("the composer on a collection that holds several languages", () => {
  it("starts on the page's language, with the others on offer", async () => {
    mockFetch();
    renderComposer();

    await waitFor(() => expect(languageRow()).toBeTruthy());
    expect(within(languageRow()).getByText(t("collections.languageMissing", { locale: "TR", field: "Başlık" }))).toBeTruthy();
    expect(screen.getByLabelText(t("collections.addLanguage", { locale: "EN" }))).toBeTruthy();
    // One language, so the form is the familiar one: a single title field.
    expect(screen.queryByLabelText("Başlık TR")).toBeNull();
  });

  it("gives each language a row for prose and asks the rest once", async () => {
    mockFetch();
    renderComposer();
    await addEnglish();

    expect(screen.getByLabelText("Başlık TR")).toBeTruthy();
    expect(screen.getByLabelText("Özet EN")).toBeTruthy();
    expect(document.querySelectorAll("input.inscribed-switch-input")).toHaveLength(1);
  });

  it("creates every language, each one after the first in the first one's group", async () => {
    mockFetch();
    const onCreated = vi.fn();
    renderComposer({ onCreated });
    await addEnglish();
    type(screen.getByLabelText("Başlık TR"), "Tanıtım günü");
    type(screen.getByLabelText("Başlık EN"), "Open day");
    fireEvent.click(document.querySelector("input.inscribed-switch-input"));
    fireEvent.click(screen.getByText(t("collections.createLocales", { locales: "TR + EN" })));

    await waitFor(() => expect(onCreated).toHaveBeenCalledTimes(1));
    const [tr, en] = creates();
    expect(tr.url.searchParams.get("locale")).toBe("tr");
    expect(tr.url.searchParams.get("translationGroup")).toBeNull();
    expect(en.url.searchParams.get("locale")).toBe("en");
    expect(en.url.searchParams.get("translationGroup")).toBe("group-tr");
    // Prose per language, everything else the same in both.
    expect(tr.body.data).toMatchObject({ title: "Tanıtım günü", featured: true });
    expect(en.body.data).toMatchObject({ title: "Open day", featured: true });

    const [item, all] = onCreated.mock.calls[0];
    expect(item.locale).toBe("tr");
    expect(all.map((row) => row.locale)).toEqual(["tr", "en"]);
  });

  it("keeps what landed and sends only the rest on retry", async () => {
    mockFetch({ failOnce: "en" });
    const onCreated = vi.fn();
    renderComposer({ onCreated });
    await addEnglish();
    type(screen.getByLabelText("Başlık TR"), "Tanıtım günü");
    type(screen.getByLabelText("Başlık EN"), "Open day");
    fireEvent.click(screen.getByText(t("collections.createLocales", { locales: "TR + EN" })));

    expect(await screen.findByRole("alert")).toBeTruthy();
    expect(screen.getByRole("alert").textContent).toContain(
      t("collections.createdPartly", { created: "TR", failed: "EN", reason: "" }).trim(),
    );
    expect(within(languageRow()).getByText(t("collections.languageCreated", { locale: "TR" }))).toBeTruthy();
    expect(onCreated).not.toHaveBeenCalled();

    fireEvent.click(screen.getByText(t("collections.retryLocales", { locales: "EN" })));
    await waitFor(() => expect(onCreated).toHaveBeenCalledTimes(1));

    // Turkish went out once; English twice, the second time into its group.
    const sent = creates().map(({ url }) => url.searchParams.get("locale"));
    expect(sent).toEqual(["tr", "en", "en"]);
    expect(creates()[2].url.searchParams.get("translationGroup")).toBe("group-tr");
  });

  it("names the language that is missing a required field, and sends nothing", async () => {
    mockFetch();
    renderComposer();
    await addEnglish();
    type(screen.getByLabelText("Başlık TR"), "Tanıtım günü");
    fireEvent.click(screen.getByText(t("collections.createLocales", { locales: "TR + EN" })));

    expect(await screen.findByText(t("collections.requiredMissingIn", { locale: "EN", field: "Başlık" }))).toBeTruthy();
    expect(creates()).toHaveLength(0);
  });

  it("opens an added language on its own draft and drops that draft when it is removed", async () => {
    mockFetch({ pending: { en: { title: "Yarım İngilizce" } } });
    renderComposer();

    // The offer says there is something waiting.
    fireEvent.click(await screen.findByLabelText(t("collections.addLanguageDraft", { locale: "EN" })));
    await waitFor(() => expect(/** @type {HTMLInputElement} */ (screen.getByLabelText("Başlık EN")).value).toBe("Yarım İngilizce"));

    fireEvent.click(screen.getByLabelText(t("collections.removeLanguage", { locale: "EN" })));
    await waitFor(() => expect(requests.some(({ method, url }) =>
      method === "DELETE" && url.pathname === `/cms/collections/${KEY}/drafts` && url.searchParams.get("locale") === "en",
    )).toBe(true));
    expect(screen.queryByLabelText("Başlık EN")).toBeNull();
  });

  it("stays a single-language form when pinned to one", async () => {
    mockFetch();
    renderComposer({ locale: "en" });

    await waitFor(() => expect(document.querySelector("input.inscribed-field")).toBeTruthy());
    expect(screen.queryByRole("group", { name: t("collections.languages") })).toBeNull();
  });
});

describe("the panel's create pane", () => {
  it("writes every language at the slug typed for it", async () => {
    mockFetch({ slugSource: "UserDefined" });
    render(
      <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
        <CollectionRegionPanel collectionKey={KEY} scope="global" />
      </CmsProvider>,
    );
    const createRow = t("collections.newRecordIn", { key: KEY });
    fireEvent.click(await screen.findByText(createRow));
    const pane = await screen.findByRole("region", { name: createRow });

    fireEvent.click(await within(pane).findByLabelText(t("collections.addLanguage", { locale: "EN" })));
    await waitFor(() => expect(within(pane).getByLabelText("Slug EN")).toBeTruthy());
    type(within(pane).getByLabelText("Slug TR"), "tanitim-gunu");
    type(within(pane).getByLabelText("Slug EN"), "open-day");
    type(within(pane).getByLabelText("Başlık TR"), "Tanıtım günü");
    type(within(pane).getByLabelText("Başlık EN"), "Open day");
    fireEvent.click(within(pane).getByText(t("collections.createLocales", { locales: "TR + EN" })));

    await waitFor(() => expect(creates()).toHaveLength(2));
    const [tr, en] = creates();
    expect(tr.method).toBe("PUT");
    expect(tr.url.pathname).toBe(`/cms/collections/${KEY}/tanitim-gunu`);
    expect(tr.body).toMatchObject({ version: null });
    expect(en.url.pathname).toBe(`/cms/collections/${KEY}/open-day`);
    expect(en.url.searchParams.get("translationGroup")).toBe("group-tr");
  });
});
