// @vitest-environment jsdom
/**
 * What a record row shows.
 *
 * The row used to lead with the slug and squeeze the record's own title into a
 * 45% tail, which made a list of content read as a table of primary keys. It
 * leads with the content now: the schema's first `Image` as a thumbnail, the
 * title at reading size, the address demoted to a second line, and the record's
 * state as a word rather than a dot.
 *
 * The thumbnail column is the schema's decision, not each record's: a
 * collection that declares an image keeps every row aligned whether or not a
 * given record filled it in, and one that declares none grows no column at all.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { CollectionRegionPanel } from "../../admin/CollectionRegionPanel.jsx";
import { createCmsConfig } from "../../shared/config.js";
import { en } from "../../shared/i18n/en/index.js";

const BASE = "https://api.test";
const KEY = "probe-news";
const CONFIG = createCmsConfig({ baseUrl: BASE });

const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const field = (name, type, extra = {}) => ({
  name, type, label: name, required: false, readOnly: false, computed: false,
  options: null, itemFields: null, help: null, ...extra,
});

const WITH_IMAGE = [field("name", "ShortText"), field("cover", "Image")];
const WITHOUT_IMAGE = [field("name", "ShortText")];

const row = (slug, name, extra = {}) => ({
  id: `row-${slug}`,
  collectionKey: KEY,
  slug,
  data: { name },
  version: 1,
  canEdit: true,
  ...extra,
});

function mockFetch(fields, items) {
  global.fetch = vi.fn(async (input) => {
    const url = String(input);
    if (url.includes("/cms/collections/me")) {
      return jsonRes([{
        collectionKey: KEY, canCreate: false, slugSource: "AutoGenerated",
        schema: { fields },
      }]);
    }
    if (url.includes(`/cms/collections/${KEY}`)) {
      return jsonRes({ items, total: items.length, offset: 0, limit: 50, virtualItems: [] });
    }
    return jsonRes({ slug: "/", blocks: [] });
  });
}

function renderPanel(fields, items) {
  mockFetch(fields, items);
  return render(
    <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
      <CollectionRegionPanel collectionKey={KEY} scope="global" />
    </CmsProvider>,
  );
}

/** The row button carrying this headline. */
const rowFor = (text) => screen.getByText(text).closest("button");

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("the record row's thumbnail", () => {
  it("shows the record's own image when the schema declares one", async () => {
    renderPanel(WITH_IMAGE, [
      row("alfa", "Alfa", { data: { name: "Alfa", cover: { src: "/alfa.jpg", alt: "" } } }),
    ]);
    await waitFor(() => expect(rowFor("Alfa")).toBeTruthy());

    const img = rowFor("Alfa")?.querySelector("img");
    expect(img?.getAttribute("src")).toBe("/alfa.jpg");
    // Decorative: the row's own text already names the record, so a screen
    // reader announcing the filename too would say it twice.
    expect(img?.getAttribute("alt")).toBe("");
  });

  // Holding the column is the whole point: without it the rows below a record
  // with no image would step left.
  it("holds the column with a placeholder when this record left it empty", async () => {
    renderPanel(WITH_IMAGE, [row("beta", "Beta")]);
    await waitFor(() => expect(rowFor("Beta")).toBeTruthy());

    const el = rowFor("Beta");
    expect(el?.querySelector("img")).toBeNull();
    // The placeholder is drawn, and it is not announced.
    expect(el?.querySelector("svg[aria-hidden], [aria-hidden] svg")).toBeTruthy();
  });

  // A collection with no images has no picture to miss, so the row leads with a
  // list marker instead of a placeholder for something that was never there.
  it("leads with a marker, not a placeholder, when the collection has no images", async () => {
    renderPanel(WITHOUT_IMAGE, [row("gama", "Gama")]);
    await waitFor(() => expect(rowFor("Gama")).toBeTruthy());

    const el = rowFor("Gama");
    expect(el?.querySelector("img")).toBeNull();
    expect(el?.querySelector(".inscribed-row-mark")).toBeTruthy();
    // The marker's track is a tenth of the thumbnail's: it anchors the text, it
    // does not reserve room for an image.
    expect(el?.style.gridTemplateColumns).toBe("10px 1fr auto");
  });

  it("reserves the full thumbnail track wherever the schema declares an image", async () => {
    renderPanel(WITH_IMAGE, [row("delta", "Delta")]);
    await waitFor(() => expect(rowFor("Delta")).toBeTruthy());

    const el = rowFor("Delta");
    expect(el?.querySelector(".inscribed-row-mark")).toBeNull();
    expect(el?.style.gridTemplateColumns).toBe("34px 1fr auto");
  });
});

describe("the record row's state", () => {
  const t = (key) => en[key] ?? key;

  it("says read-only in a word", async () => {
    renderPanel(WITHOUT_IMAGE, [row("alfa", "Alfa", { canEdit: false })]);
    await waitFor(() => expect(rowFor("Alfa")).toBeTruthy());
    expect(rowFor("Alfa")?.textContent).toContain(t("block.readOnly"));
  });

  it("says archived in a word", async () => {
    renderPanel(WITHOUT_IMAGE, [row("alfa", "Alfa", { isArchived: true })]);
    await waitFor(() => expect(rowFor("Alfa")).toBeTruthy());
    expect(rowFor("Alfa")?.textContent).toContain(t("collections.archivedBadge"));
  });

  // Three states down one list cannot be three dots; that is a legend.
  it("carries no state tag when the record is plain", async () => {
    renderPanel(WITHOUT_IMAGE, [row("alfa", "Alfa")]);
    await waitFor(() => expect(rowFor("Alfa")).toBeTruthy());

    const text = rowFor("Alfa")?.textContent ?? "";
    expect(text).not.toContain(t("block.readOnly"));
    expect(text).not.toContain(t("collections.archivedBadge"));
    expect(text).not.toContain(t("collections.draftBadge"));
  });
});

describe("the record row's two lines", () => {
  it("leads with the title and keeps the slug as the address beneath it", async () => {
    renderPanel(WITHOUT_IMAGE, [row("bahar-senligi", "Bahar Şenliği")]);
    await waitFor(() => expect(rowFor("Bahar Şenliği")).toBeTruthy());

    const el = rowFor("Bahar Şenliği");
    expect(el?.textContent).toContain("bahar-senligi");
    // The slug's tone is a class rule so the row's hover can lift it; an inline
    // colour would outrank it.
    expect(el?.querySelector(".inscribed-row-slug")?.textContent).toBe("bahar-senligi");
  });

  // With nothing textual in the schema the slug is the headline, and printing
  // it again underneath would say the same string twice.
  it("does not repeat the slug when it is the headline", async () => {
    renderPanel([field("count", "Number")], [row("yalniz", "")]);
    await waitFor(() => expect(rowFor("yalniz")).toBeTruthy());
    expect(rowFor("yalniz")?.querySelectorAll(".inscribed-row-slug").length).toBe(0);
  });
});
