// @vitest-environment jsdom
/**
 * A collection panel reads its first page once: the rows it lists and the
 * window it takes `virtualItems` from are the same rows, so they share one
 * request rather than asking twice under two spellings of the same params.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, waitFor, act } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { CollectionRegionPanel } from "../../admin/CollectionRegionPanel.jsx";
import { createCmsConfig } from "../../shared/config.js";

const KEY = "news";
const CONFIG = createCmsConfig({ baseUrl: "https://api.test" });
const jsonRes = (body) => new Response(JSON.stringify(body));
const ROWS = Array.from({ length: 3 }, (_, i) => ({
  id: `row-${i}`, collectionKey: KEY, slug: `haber-${i}`, data: { title: `Haber ${i}` }, version: 1, canEdit: true,
}));

function mockServer() {
  global.fetch = vi.fn(async (input) => {
    const url = new URL(String(input));
    if (url.pathname === "/cms/collections/me") {
      return jsonRes([{
        collectionKey: KEY, canCreate: false, slugSource: "AutoGenerated",
        displayField: "title", schema: { fields: [] },
      }]);
    }
    if (url.pathname === `/cms/collections/${KEY}`) {
      return jsonRes({ items: ROWS, total: ROWS.length, offset: 0, limit: 50, virtualItems: [] });
    }
    return jsonRes({ slug: "/", blocks: [] });
  });
}

const listRequests = () => /** @type {*} */ (global.fetch).mock.calls
  .map(([input]) => new URL(String(input)))
  .filter((url) => url.pathname === `/cms/collections/${KEY}`);

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("a collection panel opened from the rail", () => {
  it("reads its first page once", async () => {
    mockServer();
    render(
      <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
        <CollectionRegionPanel collectionKey={KEY} scope="global" />
      </CmsProvider>,
    );
    await waitFor(() => expect(screen.getByText("Haber 0")).toBeTruthy());
    await act(async () => {});

    expect(listRequests()).toHaveLength(1);
  });
});
