// @vitest-environment jsdom
/**
 * Searching a collection from the drawer.
 *
 * The search used to filter only the rows already loaded, so a record on the
 * sixth page was found by pressing "Load more" five times. It is the backend's
 * `?q=` now: the box asks once typing pauses, the answer is the server's, and
 * paging happens inside the answer rather than on the way to it.
 *
 * The server here is a stand-in that matches on the slug. What it proves is the
 * panel's side of the contract: what it sends, what it keeps on screen while it
 * waits, and how it shows an answer that is only a suggestion.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, waitFor, fireEvent } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { CollectionRegionPanel } from "../../admin/CollectionRegionPanel.jsx";
import { createCmsConfig } from "../../shared/config.js";
import { createTranslator, resolveStrings } from "../../shared/i18n/translate.js";

const t = createTranslator(resolveStrings("en"), "en");

const BASE = "https://api.test";
const KEY = "probe-catalog";
const CONFIG = createCmsConfig({ baseUrl: BASE });

const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const row = (slug, name) => ({
  id: `row-${slug}`, collectionKey: KEY, slug, data: { name }, version: 1, canEdit: true,
});

// Sixty records, so the one worth finding sits past the first page of fifty.
const RECORDS = [
  ...Array.from({ length: 59 }, (_, i) => row(`alfa-${String(i + 1).padStart(2, "0")}`, `Alfa ${i + 1}`)),
  row("zz-isik-sinavi", "Işık Sınavı"),
];

/**
 * @param {{ near?: Record<string, ReturnType<typeof row>[]>, hold?: { q: string, until: Promise<void> } }} [opts]
 *   `near` answers a query with similar rows, flagged approximate. `hold`
 *   keeps one query's answer back until its promise settles.
 */
function mockServer({ near = {}, hold } = {}) {
  global.fetch = vi.fn(async (input) => {
    const url = new URL(String(input));
    if (url.pathname === "/cms/collections/me") {
      return jsonRes([{
        collectionKey: KEY, canCreate: false, slugSource: "AutoGenerated",
        displayField: "name", schema: { fields: [] },
      }]);
    }
    if (url.pathname.startsWith(`/cms/collections/${KEY}`)) {
      const q = url.searchParams.get("q");
      const offset = Number(url.searchParams.get("offset") ?? 0);
      const limit = Number(url.searchParams.get("limit") ?? 50);
      if (q && hold?.q === q) await hold.until;
      const similar = q ? near[q] : undefined;
      const matched = similar ?? (q ? RECORDS.filter((r) => r.slug.includes(q)) : RECORDS);
      return jsonRes({
        items: matched.slice(offset, offset + limit),
        total: matched.length,
        offset,
        limit,
        virtualItems: [],
        ...(similar ? { approximate: true } : {}),
      });
    }
    return jsonRes({ slug: "/", blocks: [] });
  });
}

function renderPanel() {
  return render(
    <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
      <CollectionRegionPanel collectionKey={KEY} scope="global" />
    </CmsProvider>,
  );
}

const searchBox = () => screen.getByPlaceholderText(t("collections.searchRecords"));
const type = (value) => fireEvent.change(searchBox(), { target: { value } });
const listRequests = () => /** @type {*} */ (global.fetch).mock.calls
  .map(([input]) => new URL(String(input)))
  .filter((url) => url.pathname === `/cms/collections/${KEY}`);
const list = () => document.querySelector("[data-cms-list]");

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("searching a collection from the drawer", () => {
  it("finds a record past the first page without paging to it", async () => {
    mockServer();
    renderPanel();
    await waitFor(() => expect(screen.getByText("Alfa 1")).toBeTruthy());
    expect(screen.queryByTitle("Işık Sınavı")).toBeNull();

    type("isik");

    await waitFor(() => expect(screen.getByTitle("Işık Sınavı")).toBeTruthy());
    const asked = listRequests().filter((url) => url.searchParams.get("q") === "isik");
    expect(asked).toHaveLength(1);
    expect(asked[0].searchParams.has("offset")).toBe(false);
    expect(screen.queryByText("Alfa 1")).toBeNull();
  });

  // One request for the word, not one per letter.
  it("asks once typing pauses", async () => {
    mockServer();
    renderPanel();
    await waitFor(() => expect(screen.getByText("Alfa 1")).toBeTruthy());

    type("i");
    type("is");
    type("isi");
    type("isik");

    await waitFor(() => expect(screen.getByTitle("Işık Sınavı")).toBeTruthy());
    expect(listRequests().filter((url) => url.searchParams.has("q")).map((url) => url.searchParams.get("q")))
      .toEqual(["isik"]);
  });

  // Folded the way the backend folds: "isik" marks "Işık", in the title and in
  // the slug alike, so the row says why it is there.
  it("marks where the search hit", async () => {
    mockServer();
    renderPanel();
    await waitFor(() => expect(screen.getByText("Alfa 1")).toBeTruthy());

    type("isik");

    await waitFor(() => expect(screen.getByTitle("Işık Sınavı")).toBeTruthy());
    expect(screen.getByTitle("Işık Sınavı").querySelector("mark")?.textContent).toBe("Işık");
    expect(screen.getByTitle("zz-isik-sinavi").querySelector("mark")?.textContent).toBe("isik");
  });

  // Emptying the list and drawing a skeleton at every pause reads as flicker;
  // the last answer stays, marked busy, until the next one replaces it.
  it("keeps the last answer up while the next one loads", async () => {
    let release = () => {};
    const until = new Promise((resolve) => { release = () => resolve(undefined); });
    mockServer({ hold: { q: "isik", until } });
    renderPanel();
    await waitFor(() => expect(screen.getByText("Alfa 1")).toBeTruthy());

    type("isik");
    await waitFor(() => expect(list()?.getAttribute("aria-busy")).toBe("true"));
    expect(screen.getByText("Alfa 1")).toBeTruthy();

    release();

    await waitFor(() => expect(screen.getByTitle("Işık Sınavı")).toBeTruthy());
    expect(list()?.hasAttribute("aria-busy")).toBe(false);
    expect(screen.queryByText("Alfa 1")).toBeNull();
  });

  it("pages inside the answer, carrying the search along", async () => {
    mockServer();
    renderPanel();
    await waitFor(() => expect(screen.getByText("Alfa 1")).toBeTruthy());

    type("alfa");
    await waitFor(() => expect(screen.getByText(t("collections.loadMore", { remaining: 9 }))).toBeTruthy());
    fireEvent.click(screen.getByText(t("collections.loadMore", { remaining: 9 })));

    await waitFor(() => expect(screen.getByTitle("Alfa 59")).toBeTruthy());
    const next = listRequests().find((url) => url.searchParams.get("offset") === "50");
    expect(next?.searchParams.get("q")).toBe("alfa");
    expect(screen.queryByText(t("collections.loadMore", { remaining: 0 }))).toBeNull();
  });

  // Similar rows are suggestions, and the panel says so; nothing in them
  // matches the words, so nothing is marked either.
  it("labels an approximate answer and marks nothing in it", async () => {
    mockServer({ near: { kopke: [row("kopek", "Köpek")] } });
    renderPanel();
    await waitFor(() => expect(screen.getByText("Alfa 1")).toBeTruthy());

    type("kopke");

    await waitFor(() => expect(screen.getByText(t("collections.searchApproximate"))).toBeTruthy());
    expect(screen.getByTitle("Köpek")).toBeTruthy();
    expect(list()?.querySelector("mark")).toBeNull();
  });

  it("says so when nothing matches", async () => {
    mockServer();
    renderPanel();
    await waitFor(() => expect(screen.getByText("Alfa 1")).toBeTruthy());

    type("yokyok");

    await waitFor(() => expect(screen.getByText(t("collections.searchEmpty", { query: "yokyok" }))).toBeTruthy());
  });

  it("returns to the whole collection when the box is cleared", async () => {
    mockServer();
    renderPanel();
    await waitFor(() => expect(screen.getByText("Alfa 1")).toBeTruthy());
    type("isik");
    await waitFor(() => expect(screen.getByTitle("Işık Sınavı")).toBeTruthy());

    fireEvent.click(screen.getByLabelText(t("collections.clear")));

    await waitFor(() => expect(screen.getByText("Alfa 1")).toBeTruthy());
    expect(screen.queryByTitle("Işık Sınavı")).toBeNull();
  });
});
