// @vitest-environment jsdom
/**
 * The panel's language switch. An editor reading a Turkish page still has to be
 * able to read the English rows and write a first English record, so the
 * language the panel works in is its own state rather than the route's, and it
 * reaches both the list windows and the create pane.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, fireEvent, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/tr",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionRegionPanel } from "../../admin/CollectionRegionPanel.jsx";
import { createCmsConfig } from "../../shared/config.js";
import { createTranslator, resolveStrings } from "../../shared/i18n/translate.js";

const t = createTranslator(resolveStrings("en"), "en");

const BASE = "https://api.test";
const KEY = "probe-catalog";
const CONFIG = createCmsConfig({ baseUrl: BASE, locales: ["tr", "en"] });

const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const catalogMeta = (locales) => ({
  collectionKey: KEY,
  canCreate: true,
  slugSource: "AutoGenerated",
  locales,
  schema: {
    fields: [
      { name: "name", label: "Ad", type: "ShortText", required: true, readOnly: false, computed: false, options: null, itemFields: null, help: null },
    ],
  },
});

/** Every request as [method, url]. */
let requests;

function mockFetch(locales, extraMeta = []) {
  requests = [];
  global.fetch = vi.fn(async (input, init) => {
    const url = String(input);
    const method = init?.method ?? "GET";
    requests.push([method, url]);
    if (url.includes("/cms/collections/me")) return jsonRes([catalogMeta(locales), ...extraMeta]);
    if (method === "POST" && url.includes(`/cms/collections/${KEY}`) && !url.includes("/drafts")) {
      return jsonRes({
        id: "row-1", collectionKey: KEY, slug: "yeni", data: { name: "Yeni" },
        version: 1, locale: "en", canEdit: true,
      });
    }
    if (method !== "GET") return new Response(null, { status: 204 });
    if (url.includes(`/cms/collections/${KEY}`)) {
      return jsonRes({ items: [], total: 0, offset: 0, limit: 50, virtualItems: [] });
    }
    return jsonRes({ slug: "/", blocks: [] });
  });
}

function renderPanel(key = KEY) {
  return render(
    <CmsProvider config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
      <CollectionRegionPanel collectionKey={key} scope="global" />
    </CmsProvider>,
  );
}

/** Locales of every list read so far, in order. */
const listLocales = (key = KEY) => requests
  .filter(([m, url]) => m === "GET" && url.includes(`/cms/collections/${key}`))
  .map(([, url]) => new URL(url).searchParams.get("locale"));

const createLocale = () => {
  const hit = requests.find(([m, url]) =>
    m === "POST" && url.includes(`/cms/collections/${KEY}`) && !url.includes("/drafts"));
  return hit ? new URL(hit[1]).searchParams.get("locale") : undefined;
};

const switchTo = (code) => fireEvent.click(screen.getByTitle(t("collections.viewLocaleIs", { locale: code })));

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("the switch itself", () => {
  it("offers every language the collection declares", async () => {
    mockFetch(["tr", "en"]);
    renderPanel();
    await waitFor(() => expect(screen.getByTitle(t("collections.viewLocaleIs", { locale: "EN" }))).toBeTruthy());
    expect(screen.getByTitle(t("collections.viewLocaleIs", { locale: "TR" }))).toBeTruthy();
  });

  it("stays hidden when the collection holds no languages", async () => {
    mockFetch([]);
    renderPanel();
    await waitFor(() => expect(screen.getByPlaceholderText(t("collections.searchRecords"))).toBeTruthy());
    expect(screen.queryByTitle(t("collections.viewLocaleIs", { locale: "TR" }))).toBeNull();
  });

  it("stays hidden for a single language, which is not a choice", async () => {
    mockFetch(["tr"]);
    renderPanel();
    await waitFor(() => expect(screen.getByPlaceholderText(t("collections.searchRecords"))).toBeTruthy());
    expect(screen.queryByTitle(t("collections.viewLocaleIs", { locale: "TR" }))).toBeNull();
  });
});

describe("what the switch drives", () => {
  it("starts on the route's language and re-reads the list in the picked one", async () => {
    mockFetch(["tr", "en"]);
    renderPanel();
    await waitFor(() => expect(listLocales()).toContain("tr"));

    switchTo("EN");
    await waitFor(() => expect(listLocales()).toContain("en"));
  });

  it("drops a pick the next collection does not hold", async () => {
    // The panel is reused across collections, so a language chosen for one must
    // not follow the editor into another that was never written in it.
    const monolingual = { ...catalogMeta([]), collectionKey: "probe-events" };
    mockFetch(["tr", "en"], [monolingual]);
    const { rerender } = renderPanel();
    await waitFor(() => expect(listLocales()).toContain("tr"));
    switchTo("EN");
    await waitFor(() => expect(listLocales()).toContain("en"));

    rerender(
      <CmsProvider config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
        <CollectionRegionPanel collectionKey="probe-events" scope="global" />
      </CmsProvider>,
    );
    await waitFor(() => expect(listLocales("probe-events").length).toBeGreaterThan(0));
    // Both windows the panel reads (the rows and the pending-draft lookup) go
    // out without a language, the same as before anything was picked.
    expect(listLocales("probe-events").every((l) => l === null)).toBe(true);
  });

  it("composes a new record in the picked language, with no Turkish one to hang it on", async () => {
    mockFetch(["tr", "en"]);
    renderPanel();
    await waitFor(() => expect(screen.getByText(t("collections.newRecordInLocale", { key: KEY, locale: "TR" }))).toBeTruthy());

    switchTo("EN");
    const createRow = t("collections.newRecordInLocale", { key: KEY, locale: "EN" });
    await waitFor(() => expect(screen.getByText(createRow)).toBeTruthy());
    fireEvent.click(screen.getByText(createRow));

    await waitFor(() => expect(document.querySelectorAll("input.inscribed-field")).toHaveLength(1));
    fireEvent.change(document.querySelectorAll("input.inscribed-field")[0], { target: { value: "Yeni" } });
    fireEvent.click(screen.getByText(t("collections.create")));

    await waitFor(() => expect(createLocale()).toBe("en"));
    // No translation group: this is a first record, not a sibling of one.
    const [, url] = requests.find(([m, u]) =>
      m === "POST" && u.includes(`/cms/collections/${KEY}`) && !u.includes("/drafts"));
    expect(new URL(url).searchParams.get("translationGroup")).toBeNull();
  });
});
