// @vitest-environment jsdom
/**
 * The page's selection, marked in the drawer's row list.
 *
 * Clicking a `<CollectionItem>` on the page sets the drawer's single
 * `activeBlock` channel to that record's binding id. The row list reads it back
 * so the record being looked at on the page is the one wearing the ring in the
 * panel; without this the two surfaces each had their own idea of "current".
 *
 * The match is by the id builder's own prefix, so it has to be scoped to this
 * collection: a record named `beta` in some other collection must not light the
 * `beta` row here.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, fireEvent, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { CollectionRegionPanel } from "../../admin/CollectionRegionPanel.jsx";
import { collectionItemBindingId } from "../../collections/context.js";
import { useCmsContext } from "../../shared/state/cms-context.js";
import { createCmsConfig } from "../../shared/config.js";

const BASE = "https://api.test";
const KEY = "probe-news";
const CONFIG = createCmsConfig({ baseUrl: BASE });

const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const meta = {
  collectionKey: KEY,
  canCreate: false,
  slugSource: "AutoGenerated",
  schema: {
    fields: [
      { name: "name", label: "Ad", type: "ShortText", required: true, readOnly: false, computed: false, options: null, itemFields: null, help: null },
    ],
  },
};

const row = (slug, name) => ({
  id: `row-${slug}`,
  collectionKey: KEY,
  slug,
  data: { name },
  version: 1,
  canEdit: true,
});

function mockFetch() {
  global.fetch = vi.fn(async (input) => {
    const url = String(input);
    if (url.includes("/cms/collections/me")) return jsonRes([meta]);
    if (url.includes(`/cms/collections/${KEY}`)) {
      return jsonRes({
        items: [row("alfa", "Alfa"), row("beta", "Beta")],
        total: 2,
        offset: 0,
        limit: 50,
        virtualItems: [],
      });
    }
    return jsonRes({ slug: "/", blocks: [] });
  });
}

/** Stands in for a page-side `<CollectionItem>` being clicked. */
function Selector({ bindingId }) {
  const { setActiveBlock } = useCmsContext();
  return (
    <button type="button" onClick={() => setActiveBlock(bindingId)}>
      select
    </button>
  );
}

function renderPanel(bindingId) {
  mockFetch();
  return render(
    <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
      <Selector bindingId={bindingId} />
      <CollectionRegionPanel collectionKey={KEY} scope="global" />
    </CmsProvider>,
  );
}

/** The row button carrying this headline. */
const rowFor = (text) => screen.getByText(text).closest("button");

const select = () => fireEvent.click(screen.getByRole("button", { name: "select" }));

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("the page's selection in the row list", () => {
  it("marks nothing while the page has selected nothing", async () => {
    renderPanel(collectionItemBindingId(KEY, "beta"));
    await waitFor(() => expect(rowFor("Beta")).toBeTruthy());

    expect(rowFor("Alfa")?.className).not.toContain("is-active");
    expect(rowFor("Beta")?.className).not.toContain("is-active");
  });

  it("rings the row the page is pointing at, and only that one", async () => {
    renderPanel(collectionItemBindingId(KEY, "beta"));
    await waitFor(() => expect(rowFor("Beta")).toBeTruthy());

    select();

    await waitFor(() => expect(rowFor("Beta")?.className).toContain("is-active"));
    expect(rowFor("Alfa")?.className).not.toContain("is-active");
  });

  // The ring is a visual mark, so the row says the same thing to a reader that
  // cannot see it.
  it("says which row is current to a screen reader too", async () => {
    renderPanel(collectionItemBindingId(KEY, "beta"));
    await waitFor(() => expect(rowFor("Beta")).toBeTruthy());

    select();

    await waitFor(() => expect(rowFor("Beta")?.getAttribute("aria-current")).toBe("true"));
    expect(rowFor("Alfa")?.getAttribute("aria-current")).toBeNull();
  });

  // Collection bindings share one channel with content blocks and with every
  // other collection, so a same-named record elsewhere must not reach in here.
  it("ignores a selection in another collection with the same slug", async () => {
    renderPanel(collectionItemBindingId("other-collection", "beta"));
    await waitFor(() => expect(rowFor("Beta")).toBeTruthy());

    select();

    // Nothing to wait for, so settle the update and then assert it stayed clean.
    await waitFor(() => expect(rowFor("Beta")).toBeTruthy());
    expect(rowFor("Beta")?.className).not.toContain("is-active");
    expect(rowFor("Alfa")?.className).not.toContain("is-active");
  });

  // A content block's path is not a collection binding at all, and the prefix
  // test is what keeps it from being read as one.
  it("ignores a plain content block being selected", async () => {
    renderPanel("hero.title");
    await waitFor(() => expect(rowFor("Beta")).toBeTruthy());

    select();

    await waitFor(() => expect(rowFor("Beta")).toBeTruthy());
    expect(rowFor("Beta")?.className).not.toContain("is-active");
  });
});
