// @vitest-environment jsdom
/**
 * The composer's autosaved draft has to survive closing the form. The backend
 * holds it the moment the request lands, but nothing refetches the list between
 * keystrokes, so the cached `pending` virtual row is what the next mount seeds
 * from. Before the provider patched that row, reopening the form showed an
 * empty one and only a page reload brought the text back.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, act, fireEvent, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/haberler",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionComposer } from "../../collections/CollectionComposer.jsx";

const BASE = "https://api.test";

const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const newsMeta = {
  collectionKey: "news",
  canCreate: true,
  slugSource: "AutoGenerated",
  schema: {
    fields: [
      { name: "title", label: "Başlık", type: "ShortText", required: true, readOnly: false, computed: false, options: null, itemFields: null, help: null },
    ],
  },
};

/** Every request as [method, url]. */
let requests;

function mockFetch() {
  requests = [];
  global.fetch = vi.fn(async (input, init) => {
    const url = String(input);
    const method = init?.method ?? "GET";
    requests.push([method, url]);
    if (url.includes("/cms/collections/me")) return jsonRes([newsMeta]);
    if (method !== "GET") return new Response(null, { status: 204 });
    if (url.includes("/cms/collections/news")) {
      // No pending row: the backend sends one only once a draft exists.
      return jsonRes({ items: [], total: 0, offset: 0, limit: 50, virtualItems: [] });
    }
    return jsonRes({ slug: "/haberler", blocks: [] });
  });
}

/** The provider outlives the composer, so the cache survives an unmount. */
function Harness({ open }) {
  return (
    <CmsProvider config={{ baseUrl: BASE }} isAdmin getAccessToken={async () => "tok"}>
      {open ? <CollectionComposer collection="news" /> : null}
    </CmsProvider>
  );
}

const titleInput = () => document.querySelector("input.inscribed-field");
const draftPosts = () => requests.filter(([m, u]) => m === "POST" && u.endsWith("/cms/collections/news/drafts"));
const listGets = () => requests.filter(([m, u]) => m === "GET" && u.includes("/cms/collections/news"));

/** Type, then let the autosave debounce elapse. */
async function typeAndFlush(value) {
  vi.useFakeTimers();
  try {
    fireEvent.change(titleInput(), { target: { value } });
    await act(async () => {
      await vi.advanceTimersByTimeAsync(2000);
    });
  } finally {
    vi.useRealTimers();
  }
}

afterEach(() => {
  cleanup();
  vi.useRealTimers();
  vi.restoreAllMocks();
});

describe("the autosaved new-item draft", () => {
  it("seeds the form again after the composer is closed and reopened", async () => {
    mockFetch();
    const { rerender } = render(<Harness open />);
    await waitFor(() => expect(titleInput()).toBeTruthy());

    await typeAndFlush("Yarım haber");
    expect(draftPosts()).toHaveLength(1);

    const listsBefore = listGets().length;
    rerender(<Harness open={false} />);
    await waitFor(() => expect(titleInput()).toBeNull());
    rerender(<Harness open />);

    await waitFor(() => expect(titleInput()?.value).toBe("Yarım haber"));
    // Seeded from the cache the autosave patched, not from a fresh read.
    expect(listGets()).toHaveLength(listsBefore);
  });

  it("does not re-seed over keystrokes typed while the autosave was in flight", async () => {
    mockFetch();
    render(<Harness open />);
    await waitFor(() => expect(titleInput()).toBeTruthy());

    await typeAndFlush("Yarım");
    fireEvent.change(titleInput(), { target: { value: "Yarım haber" } });

    // The patched row carries the older payload; the form must keep the newer.
    await waitFor(() => expect(titleInput()?.value).toBe("Yarım haber"));
  });
});
