// @vitest-environment jsdom
/**
 * A record placed on the page, in a collection that holds several languages.
 *
 * Its drawer card carries the record's other languages: the sibling records its
 * translation group has, and for a language it lacks, a form whose record the
 * card creates when it publishes. The claims under test: the card's save sends
 * the record and every language written from the card, the record first; a
 * sibling's draft left from elsewhere stays out until it is written here; a
 * missing language is created from what was typed plus the record's other
 * values, in the record's group; every language is checked before anything is
 * sent; and a language that fails is named and retried on its own.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React, { useEffect } from "react";
import { render, screen, cleanup, fireEvent, waitFor, within } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/haberler",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { CollectionLane } from "../../admin/CollectionBlockCard.jsx";
import { useCmsContext } from "../../shared/state/cms-context.js";
import { createCmsConfig } from "../../shared/config.js";
import { createTranslator, resolveStrings } from "../../shared/i18n/translate.js";

const t = createTranslator(resolveStrings("en"), "en");

const BASE = "https://api.test";
const KEY = "news";
const CONFIG = createCmsConfig({ baseUrl: BASE, locales: ["tr", "en"] });

const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const field = (name, label, type, required = false) => ({
  name, label, type, required, readOnly: false, computed: false, options: null, itemFields: null, help: null,
});

const FIELDS = [
  field("title", "Başlık", "ShortText", true),
  field("summary", "Özet", "LongText"),
  field("cover", "Kapak", "Image"),
  field("date", "Tarih", "Date"),
];

const COVER = { src: "/bahar.jpg", alt: "Bahar afişi" };

/** Rows by slug, the way the backend holds them. */
let rows;
/** Every write as { method, url, body }, in the order it was sent. */
let writes;
/** When set, the next create answers 500 once. */
let failCreateOnce;

function turkish(translations = []) {
  return {
    id: "row-tr",
    collectionKey: KEY,
    slug: "bahar",
    locale: "tr",
    translationGroupId: "group-1",
    translations,
    data: { title: "Bahar", summary: "Türkçe özet", cover: COVER, date: "2026-05-14" },
    draftData: null,
    version: 5,
    canEdit: true,
  };
}

function english(draftData = null) {
  return {
    id: "row-en",
    collectionKey: KEY,
    slug: "spring",
    locale: "en",
    translationGroupId: "group-1",
    translations: [{ locale: "tr", slug: "bahar" }],
    data: { title: "Spring", summary: "English summary", cover: COVER, date: "2026-05-14" },
    draftData,
    version: 2,
    canEdit: true,
  };
}

/**
 * @param {{ withEnglish?: boolean, englishDraft?: object | null, slugSource?: string }} [options]
 */
function mockFetch({ withEnglish = false, englishDraft = null, slugSource = "AutoGenerated" } = {}) {
  rows = { bahar: turkish(withEnglish ? [{ locale: "en", slug: "spring" }] : []) };
  if (withEnglish) rows.spring = english(englishDraft);
  writes = [];
  failCreateOnce = false;
  global.fetch = vi.fn(async (input, init) => {
    const url = new URL(String(input));
    const method = init?.method ?? "GET";
    const body = init?.body ? JSON.parse(String(init.body)) : null;
    const path = url.pathname;
    if (path === "/cms/collections/me") {
      return jsonRes([{ collectionKey: KEY, canCreate: true, slugSource, locales: ["tr", "en"], schema: { fields: FIELDS } }]);
    }
    if (method !== "GET") writes.push({ method, url, body });

    const draft = path.match(/^\/cms\/collections\/news\/([^/]+)\/draft$/);
    if (draft) {
      if (rows[draft[1]]) rows[draft[1]].draftData = method === "PUT" ? body.data : null;
      return new Response(null, { status: 204 });
    }
    const one = path.match(/^\/cms\/collections\/news\/([^/]+)$/);
    if (one && method === "GET") {
      const row = rows[one[1]];
      return row ? jsonRes(row) : jsonRes({ title: "Not found", status: 404 }, 404);
    }
    const creates = (method === "POST" && path === "/cms/collections/news")
      || (method === "PUT" && one && !rows[one[1]]);
    if (creates) {
      if (failCreateOnce) {
        failCreateOnce = false;
        return jsonRes({ title: "Server error", status: 500, detail: "boom" }, 500);
      }
      const locale = url.searchParams.get("locale");
      const slug = one ? one[1] : `${locale}-${String(body.data.title).toLowerCase().replace(/\s+/g, "-")}`;
      rows[slug] = {
        id: `row-${slug}`,
        collectionKey: KEY,
        slug,
        locale,
        translationGroupId: url.searchParams.get("translationGroup"),
        translations: [{ locale: "tr", slug: "bahar" }],
        data: body.data,
        draftData: null,
        version: 1,
        canEdit: true,
      };
      return jsonRes(rows[slug]);
    }
    if (one && method === "PUT") {
      const row = rows[one[1]];
      if (body.version !== row.version) return jsonRes({ title: "Conflict", status: 409 }, 409);
      rows[one[1]] = { ...row, data: body.data, draftData: null, version: row.version + 1 };
      return jsonRes(rows[one[1]]);
    }
    if (path.startsWith("/cms/collections/news")) return jsonRes({ items: [], total: 0, offset: 0, limit: 50 });
    return jsonRes({ slug: "/haberler", blocks: [] });
  });
}

/** The record writes, not the draft autosave. */
const publishes = () => writes.filter(({ url }) => !url.pathname.endsWith("/draft"));

function OpenDrawer() {
  const { setDrawerOpen } = useCmsContext();
  useEffect(() => { setDrawerOpen(true); }, [setDrawerOpen]);
  return null;
}

const lane = (
  <CollectionLane
    block={/** @type {*} */ ({ blockPath: "news:bahar", blockType: "Collection", value: { collection: KEY, slug: "bahar" }, version: 0, sortOrder: 1 })}
    isActive={false}
    topLevel
  />
);

function tree(withLane = true) {
  return (
    <CmsProvider collections={CollectionProvider} config={CONFIG} isAdmin getAccessToken={async () => "tok"}>
      <OpenDrawer />
      {withLane ? lane : null}
    </CmsProvider>
  );
}

const panel = () => screen.getByRole("group", { name: t("translations.label") });

async function openLanguages() {
  fireEvent.click(await screen.findByRole("button", { name: t("translations.editOthersLabel", { path: "news:bahar" }) }));
  await waitFor(() => expect(panel()).toBeTruthy());
}

/** The record's own title field, the first "Başlık" on the card. */
const ownTitle = () => /** @type {HTMLInputElement} */ (screen.getAllByLabelText(/^Başlık/)[0]);
const englishTitle = () => /** @type {HTMLInputElement} */ (within(panel()).getByLabelText(/^Başlık/));

/** @param {HTMLElement} input @param {string} value */
const type = (input, value) => fireEvent.change(input, { target: { value } });

const saveButton = (label) => screen.getByRole("button", { name: label });

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("a sibling the record already has", () => {
  it("opens on that record's draft", async () => {
    mockFetch({ withEnglish: true, englishDraft: { ...english().data, title: "Spring, half rewritten" } });
    render(tree());
    await openLanguages();

    await waitFor(() => expect(englishTitle().value).toBe("Spring, half rewritten"));
  });

  it("publishes a translation written here along with the record, the record first", async () => {
    mockFetch({ withEnglish: true });
    render(tree());
    await openLanguages();
    await waitFor(() => expect(englishTitle().value).toBe("Spring"));

    type(ownTitle(), "Bahar Şenliği");
    type(englishTitle(), "Spring Festival");
    fireEvent.click(saveButton(t("status.saveLocales", { locales: "TR + EN" })));

    await waitFor(() => expect(publishes()).toHaveLength(2));
    const [tr, en] = publishes();
    expect(tr.url.pathname).toBe("/cms/collections/news/bahar");
    expect(tr.body).toMatchObject({ version: 5, data: { title: "Bahar Şenliği" } });
    expect(en.url.pathname).toBe("/cms/collections/news/spring");
    expect(en.body).toMatchObject({ version: 2, data: { title: "Spring Festival" } });
  });

  it("leaves a draft written elsewhere out until it is written here", async () => {
    mockFetch({ withEnglish: true, englishDraft: { ...english().data, title: "Spring, half rewritten" } });
    render(tree());
    await openLanguages();
    await waitFor(() => expect(englishTitle().value).toBe("Spring, half rewritten"));

    type(ownTitle(), "Bahar Şenliği");
    // Only the record's own language: nothing on this card chose English.
    fireEvent.click(saveButton(t("status.save")));

    await waitFor(() => expect(publishes()).toHaveLength(1));
    expect(publishes()[0].url.pathname).toBe("/cms/collections/news/bahar");
  });
});

describe("a language the record lacks", () => {
  it("is created from what was typed and the record's other values, in its group", async () => {
    mockFetch();
    render(tree());
    await openLanguages();
    expect(within(panel()).getByText(t("collections.translationMissing", { locale: "EN" }))).toBeTruthy();

    type(englishTitle(), "Spring Festival");
    type(within(panel()).getByLabelText(/^Özet/), "Three days of concerts.");
    fireEvent.click(saveButton(t("status.saveLocales", { locales: "EN" })));

    await waitFor(() => expect(publishes()).toHaveLength(1));
    const [create] = publishes();
    expect(create.method).toBe("POST");
    expect(create.url.searchParams.get("locale")).toBe("en");
    expect(create.url.searchParams.get("translationGroup")).toBe("group-1");
    // Prose as typed; the image and the date are the record's own.
    expect(create.body.data).toEqual({
      title: "Spring Festival",
      summary: "Three days of concerts.",
      cover: COVER,
      date: "2026-05-14",
    });

    // Now a sibling like any other, read from the record it just became.
    await waitFor(() => expect(within(panel()).queryByText(t("collections.translationMissing", { locale: "EN" }))).toBeNull());
    await waitFor(() => expect(englishTitle().value).toBe("Spring Festival"));
  });

  it("asks for a slug where the collection's slugs are typed, and creates at it", async () => {
    mockFetch({ slugSource: "UserDefined" });
    render(tree());
    await openLanguages();

    type(englishTitle(), "Spring Festival");
    fireEvent.click(saveButton(t("status.saveLocales", { locales: "EN" })));
    expect(await screen.findByText(t("collections.slugMissingIn", { locale: "EN" }))).toBeTruthy();
    expect(publishes()).toHaveLength(0);

    type(within(panel()).getByRole("textbox", { name: /slug/i }), "spring-festival");
    fireEvent.click(saveButton(t("status.saveLocales", { locales: "EN" })));

    await waitFor(() => expect(publishes()).toHaveLength(1));
    const [create] = publishes();
    expect(create.method).toBe("PUT");
    expect(create.url.pathname).toBe("/cms/collections/news/spring-festival");
    expect(create.url.searchParams.get("translationGroup")).toBe("group-1");
    expect(create.body.version).toBeNull();
  });

  it("checks every language before anything is sent", async () => {
    mockFetch();
    render(tree());
    await openLanguages();

    type(ownTitle(), "Bahar Şenliği");
    // A summary but no title, which the record needs.
    type(within(panel()).getByLabelText(/^Özet/), "Three days of concerts.");
    fireEvent.click(saveButton(t("status.saveLocales", { locales: "TR + EN" })));

    expect(await screen.findByText(t("collections.requiredMissingIn", { locale: "EN", field: "Başlık" }))).toBeTruthy();
    // The record itself was fine, and still did not go out alone.
    expect(publishes()).toHaveLength(0);
  });

  it("names the language that failed and retries only that one", async () => {
    mockFetch();
    render(tree());
    await openLanguages();
    failCreateOnce = true;

    type(ownTitle(), "Bahar Şenliği");
    type(englishTitle(), "Spring Festival");
    fireEvent.click(saveButton(t("status.saveLocales", { locales: "TR + EN" })));

    const alert = await screen.findByRole("alert");
    expect(alert.textContent).toContain(t("saveError.partial", { published: "TR", failed: "EN", reason: "" }).trim());

    fireEvent.click(saveButton(t("status.retryLocales", { locales: "EN" })));
    await waitFor(() => expect(publishes().filter((w) => w.method === "POST")).toHaveLength(2));
    // The record went out once; only English was sent again.
    expect(publishes().filter((w) => w.url.pathname === "/cms/collections/news/bahar")).toHaveLength(1);
  });

  it("keeps what was typed through the card leaving and coming back", async () => {
    mockFetch();
    const view = render(tree());
    await openLanguages();
    type(englishTitle(), "Spring Festival");

    view.rerender(tree(false));
    view.rerender(tree());

    // Open on arrival, without asking for it: what waits in it can only be
    // sent from here.
    fireEvent.click(await screen.findByRole("button", { expanded: false }));
    await waitFor(() => expect(englishTitle().value).toBe("Spring Festival"));
  });
});
