// @vitest-environment jsdom
/**
 * Renaming a record's slug: the gate in front of it, the version it consumes,
 * and the two 409s that are specific to this call.
 *
 * The alias conflict is the interesting one. It is recoverable, but only by
 * taking an address off another record, so the hook surfaces it as a question
 * (`renameConflict`) instead of retrying with `replaceAlias` on its own. These
 * tests pin that: one refused attempt, no second request, until the caller asks
 * for it explicitly.
 */
import { describe, it, expect, afterEach, beforeEach, vi } from "vitest";
import React from "react";
import { render, cleanup, act, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/haberler",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { useCollectionContext } from "../../collections/context.js";
import { useCollectionEditor } from "../../collections/hooks/use-collection-editor.js";
import { CmsApiError } from "../../shared/contracts/errors.js";
import { en } from "../../shared/i18n/en/index.js";

const COLLECTION = "news";
const SLUG = "eski-adres";
const NEXT_SLUG = "yeni-adres";

const SCHEMA = {
  fields: [{
    name: "title",
    label: "Başlık",
    type: "ShortText",
    required: false,
    readOnly: false,
    computed: false,
    filterable: false,
    sortable: false,
    options: null,
    itemFields: null,
    help: null,
  }],
};

let server;
let calls;
let revalidated;
let renamedTo;

const probe = /** @type {{ editor: *, store: * }} */ ({});

function Harness({ slug }) {
  probe.editor = useCollectionEditor(COLLECTION, slug, {
    onRenamed: (next) => { renamedTo.push(next); },
  });
  // Repointing moves state between two slugs' slices, so the assertions need to
  // see the store rather than just this surface's view of it.
  probe.store = useCollectionContext().collectionStore;
  return null;
}

async function settle() {
  await act(async () => {});
}

async function tick(ms = 1000) {
  await act(async () => { vi.advanceTimersByTime(ms); });
}

/** The shared draft held for one slug, or undefined. */
const draftAt = (slug) => probe.store.get().drafts.get(`${COLLECTION}:${slug}`);

const row = () => (server.virtual ? {
  collectionKey: COLLECTION,
  origin: "derived",
  slug: server.slug,
  canEdit: true,
  data: {},
} : {
  id: "row-1",
  collectionKey: COLLECTION,
  slug: server.slug,
  data: { title: "Eski haber" },
  version: server.version,
  canEdit: server.canEdit,
  ...(server.draftData ? { draftData: server.draftData } : null),
  ...(server.archived ? { isArchived: true, archivedAt: "2026-08-11T06:06:46Z" } : null),
});

/**
 * What every write path answers when the slug it was called at is an old
 * address. The backend refuses rather than following the alias, so the client
 * can learn its address is stale instead of writing to a record it never named.
 */
const refuseIfMoved = (slug) => {
  if (server.movedFrom !== slug) return;
  throw new CmsApiError({
    status: 409,
    detail: `Slug '${slug}' is an old address; the item now lives at '${server.slug}'.`,
    reason: "moved",
    conflictingSlug: server.slug,
  });
};

const transport = {
  getContent: async () => ({ slug: "/haberler", blocks: [] }),
  getMyCollections: async () => [{
    collectionKey: COLLECTION,
    canCreate: true,
    slugSource: "AutoGenerated",
    schema: SCHEMA,
    ...(server.slugEditable === undefined ? null : { slugEditable: server.slugEditable }),
  }],
  getCollectionItem: async () => row(),
  getCollection: async () => ({ items: [row()], total: 1, offset: 0, limit: 50 }),
  renameCollectionItem: async (key, slug, payload, opts) => {
    calls.push({
      from: slug,
      to: payload.slug,
      version: payload.version,
      replaceAlias: opts?.replaceAlias ?? false,
    });
    refuseIfMoved(slug);
    if (payload.version !== server.version) {
      throw new CmsApiError({ status: 409, detail: `Expected ${server.version}` });
    }
    if (server.taken === payload.slug) {
      throw new CmsApiError({
        status: 409,
        detail: `Slug '${payload.slug}' is already taken in '${key}'.`,
        reason: "taken",
        conflictingSlug: payload.slug,
      });
    }
    if (server.aliasOf?.[payload.slug] && !opts?.replaceAlias) {
      throw new CmsApiError({
        status: 409,
        detail: `Slug '${payload.slug}' is an old address of '${server.aliasOf[payload.slug]}'.`,
        reason: "alias",
        conflictingSlug: server.aliasOf[payload.slug],
      });
    }
    server.slug = payload.slug;
    server.version += 1;
    return row();
  },
  upsertCollectionItem: async (key, slug) => {
    calls.push({ upsert: slug });
    refuseIfMoved(slug);
    server.version += 1;
    return row();
  },
  archiveCollectionItem: async (key, slug, version) => {
    calls.push({ archive: slug, version });
    refuseIfMoved(slug);
    server.archived = true;
    return { collectionKey: key, slug, version };
  },
  restoreCollectionItem: async (key, slug) => {
    calls.push({ restore: slug });
    refuseIfMoved(slug);
    server.archived = false;
    return row();
  },
  saveCollectionItemDraft: async (key, slug) => {
    calls.push({ draft: slug });
    refuseIfMoved(slug);
  },
  // Answers at an old address on purpose: it is the one call a repointing
  // client still needs there, to clear the slot it is walking away from.
  deleteCollectionItemDraft: async (key, slug) => {
    calls.push({ dropDraft: slug });
  },
};

async function mount(slug = SLUG, transportOverride) {
  const view = await act(async () => render(
    <CmsProvider collections={CollectionProvider}
      config={{ baseUrl: "https://api.test" }}
      transport={/** @type {*} */ (transportOverride ?? transport)}
      onAfterCollectionSave={(key, s) => { revalidated.push(`${key}/${s}`); }}
      isAdmin
    >
      <Harness slug={slug} />
    </CmsProvider>,
  ));
  await settle();
  return view;
}

beforeEach(() => {
  server = {
    slug: SLUG,
    version: 4,
    canEdit: true,
    archived: false,
    virtual: false,
    slugEditable: true,
    draftData: null,
    taken: null,
    aliasOf: null,
    movedFrom: null,
  };
  calls = [];
  revalidated = [];
  renamedTo = [];
});

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("canRename", () => {
  it("needs both the collection flag and the row's own permission", async () => {
    await mount();
    expect(probe.editor.canRename).toBe(true);
  });

  it("is false when the collection is closed to renames", async () => {
    server.slugEditable = false;
    await mount();
    expect(probe.editor.canRename).toBe(false);
  });

  it("is false when the backend sends no flag at all", async () => {
    // Absent is not permission: an older backend has no rename endpoint, and
    // offering the button there earns a 400 the user can do nothing about.
    server.slugEditable = undefined;
    await mount();
    expect(probe.editor.canRename).toBe(false);
  });

  it("is false on a row this user cannot edit", async () => {
    server.canEdit = false;
    await mount();
    expect(probe.editor.canRename).toBe(false);
  });

  it("is false on a row that was never saved", async () => {
    server.virtual = true;
    await mount();
    expect(probe.editor.canRename).toBe(false);
  });

  it("is false on an archived row", async () => {
    server.archived = true;
    await mount();
    expect(probe.editor.canRename).toBe(false);
  });
});

describe("renaming", () => {
  it("sends the row's current version and reports the new slug", async () => {
    await mount();

    act(() => { probe.editor.rename(NEXT_SLUG); });
    await waitFor(() => expect(renamedTo).toEqual([NEXT_SLUG]));

    expect(calls).toEqual([
      { from: SLUG, to: NEXT_SLUG, version: 4, replaceAlias: false },
    ]);
  });

  it("revalidates both addresses", async () => {
    // The old one is still cached as a 200 that has to become a redirect, and
    // the new one has no entry at all yet.
    await mount();

    act(() => { probe.editor.rename(NEXT_SLUG); });
    await waitFor(() => expect(renamedTo).toEqual([NEXT_SLUG]));

    expect(revalidated).toEqual([`${COLLECTION}/${SLUG}`, `${COLLECTION}/${NEXT_SLUG}`]);
  });

  it("is a no-op when the target is the slug it already has", async () => {
    await mount();

    act(() => { probe.editor.rename(`  ${SLUG}  `); });
    await settle();
    expect(calls).toEqual([]);
  });

  it("is a no-op on an empty target", async () => {
    await mount();

    act(() => { probe.editor.rename("   "); });
    await settle();
    expect(calls).toEqual([]);
  });

  it("refuses while the row has unsaved changes", async () => {
    // The call bumps the version, so a draft autosave still holding the old one
    // would answer 409 from here on, aimed at an address that just became an
    // alias.
    await mount();

    act(() => { probe.editor.setValues({ title: "Değişti" }); });
    act(() => { probe.editor.rename(NEXT_SLUG); });
    await settle();

    expect(calls).toEqual([]);
    expect(probe.editor.error).toBe(en["collections.renameDirty"]);
  });

  it("refuses while a draft is stashed on the server", async () => {
    server.draftData = { title: "Yarım kalmış" };
    await mount();

    act(() => { probe.editor.rename(NEXT_SLUG); });
    await settle();

    expect(calls).toEqual([]);
    expect(probe.editor.error).toBe(en["collections.renameDirty"]);
  });
});

describe("a transport that cannot rename", () => {
  // A hand-written transport predating the endpoint, or one pointed at a
  // backend that has no rename at all. Absence is an answer, not a gap: the
  // affordance disappears, and nothing throws if something calls it anyway.
  const { renameCollectionItem, ...withoutRename } = transport;

  it("reads a missing method as no, even when the collection allows renames", async () => {
    await mount(SLUG, withoutRename);
    expect(probe.editor.canRename).toBe(false);
  });

  it("no-ops instead of throwing when called directly", async () => {
    await mount(SLUG, withoutRename);

    act(() => { probe.editor.rename(NEXT_SLUG); });
    await settle();

    expect(probe.editor.error).toBe(null);
    expect(renamedTo).toEqual([]);
  });
});

describe("conflicts", () => {
  it("reports a taken slug as an error, naming what is in the way", async () => {
    server.taken = NEXT_SLUG;
    await mount();

    act(() => { probe.editor.rename(NEXT_SLUG); });
    await waitFor(() => expect(probe.editor.error).toBe(
      en["collections.renameTaken"].replace("{slug}", NEXT_SLUG),
    ));
    expect(probe.editor.renameConflict).toBe(null);
  });

  it("surfaces an alias clash as a question rather than retrying it", async () => {
    server.aliasOf = { [NEXT_SLUG]: "baska-kayit" };
    await mount();

    act(() => { probe.editor.rename(NEXT_SLUG); });
    await waitFor(() => expect(probe.editor.renameConflict).toEqual({
      slug: NEXT_SLUG,
      conflictingSlug: "baska-kayit",
    }));

    // One attempt, and `replaceAlias` was not smuggled into it: taking the
    // address breaks the other record's links, so it waits for a yes.
    expect(calls).toHaveLength(1);
    expect(calls[0].replaceAlias).toBe(false);
    expect(probe.editor.error).toBe(null);
    expect(renamedTo).toEqual([]);
  });

  it("goes through once the caller confirms", async () => {
    server.aliasOf = { [NEXT_SLUG]: "baska-kayit" };
    await mount();

    act(() => { probe.editor.rename(NEXT_SLUG); });
    await waitFor(() => expect(probe.editor.renameConflict).not.toBe(null));

    act(() => { probe.editor.rename(NEXT_SLUG, { replaceAlias: true }); });
    await waitFor(() => expect(renamedTo).toEqual([NEXT_SLUG]));

    expect(calls).toHaveLength(2);
    expect(calls[1].replaceAlias).toBe(true);
    expect(probe.editor.renameConflict).toBe(null);
  });

  it("reports a stale version as a plain version conflict", async () => {
    await mount();
    // Someone else published in between, so the number in hand is behind.
    server.version = 9;

    act(() => { probe.editor.rename(NEXT_SLUG); });
    await waitFor(() => expect(probe.editor.error).toBe(en["collections.versionConflict"]));
    expect(probe.editor.renameConflict).toBe(null);
  });

  it("reports a collection closed to renames from the 400", async () => {
    await mount(SLUG, {
      ...transport,
      renameCollectionItem: async () => {
        throw new CmsApiError({ status: 400, detail: "Collection does not allow renames." });
      },
    });

    act(() => { probe.editor.rename(NEXT_SLUG); });
    await waitFor(() => expect(probe.editor.error).toBe(en["collections.renameDisabled"]));
  });
});

describe("writing to an address the record already left", () => {
  // The stale-tab case: someone else renamed the row, this surface is still
  // holding the old slug, and every write path answers `reason: "moved"` with
  // the current address rather than following the alias.
  const moved = () => { server.movedFrom = SLUG; server.slug = NEXT_SLUG; };
  const movedMessage = () =>
    en["collections.recordMoved"].replace("{slug}", NEXT_SLUG);

  it("repoints a publish instead of replaying it at the new address", async () => {
    // Replaying would be the dangerous read of "retry": this tab's version is
    // as stale as its slug, so the payload could overwrite whatever landed at
    // the canonical address.
    moved();
    await mount();

    act(() => { probe.editor.setValues({ title: "Değişti" }); });
    act(() => { probe.editor.save(); });
    await waitFor(() => expect(renamedTo).toEqual([NEXT_SLUG]));

    expect(probe.editor.error).toBe(movedMessage());
    expect(calls.filter((c) => c.upsert)).toEqual([{ upsert: SLUG }]);
  });

  it("carries the unsaved text over to the new address", async () => {
    // The write was refused, so the text is still unpublished and now has
    // somewhere valid to go. Losing it here would make being told worse than
    // being silently redirected.
    moved();
    await mount();

    act(() => { probe.editor.setValues({ title: "Yarım cümle" }); });
    expect(draftAt(SLUG)).toEqual({ title: "Yarım cümle" });

    act(() => { probe.editor.save(); });
    await waitFor(() => expect(renamedTo).toEqual([NEXT_SLUG]));

    expect(draftAt(NEXT_SLUG)).toEqual({ title: "Yarım cümle" });
    expect(draftAt(SLUG)).toBeUndefined();
  });

  it("clears the slot it walks away from", async () => {
    // Otherwise this user's half-written text sits at an address nothing reads
    // until its TTL runs out. Deleting is the one call the old address answers.
    moved();
    await mount();

    act(() => { probe.editor.setValues({ title: "Yarım cümle" }); });
    act(() => { probe.editor.save(); });
    await waitFor(() => expect(renamedTo).toEqual([NEXT_SLUG]));
    await waitFor(() => expect(calls).toContainEqual({ dropDraft: SLUG }));
  });

  it("repoints an archive", async () => {
    moved();
    await mount();

    act(() => { probe.editor.archive(); });
    await waitFor(() => expect(renamedTo).toEqual([NEXT_SLUG]));
    expect(probe.editor.error).toBe(movedMessage());
  });

  it("repoints a restore", async () => {
    // Restore was the one path that used to 404 here rather than 409.
    server.archived = true;
    moved();
    await mount();

    act(() => { probe.editor.restore(); });
    await waitFor(() => expect(renamedTo).toEqual([NEXT_SLUG]));
    expect(probe.editor.error).toBe(movedMessage());
  });

  it("repoints a rename without mistaking it for an alias clash", async () => {
    // Same status and a `conflictingSlug` either way: only `reason` separates
    // "you called the wrong address" from "the address you want is taken", and
    // they want opposite responses.
    moved();
    await mount();

    act(() => { probe.editor.rename("baska-adres"); });
    await waitFor(() => expect(renamedTo).toEqual([NEXT_SLUG]));

    expect(probe.editor.error).toBe(movedMessage());
    expect(probe.editor.renameConflict).toBe(null);
    expect(calls.filter((c) => c.replaceAlias === true)).toEqual([]);
  });
});

describe("a draft autosaved to an address that moved", () => {
  beforeEach(() => { vi.useFakeTimers(); });
  afterEach(() => { vi.useRealTimers(); });

  it("resumes at the new address rather than reporting a failed save", async () => {
    // The one write that can carry straight over: a draft has no version to
    // clash on and it is the same user's own text.
    server.movedFrom = SLUG;
    server.slug = NEXT_SLUG;
    await mount();

    act(() => { probe.editor.setValues({ title: "Yazmaya devam" }); });
    await tick();
    await settle();

    expect(renamedTo).toEqual([NEXT_SLUG]);
    expect(draftAt(NEXT_SLUG)).toEqual({ title: "Yazmaya devam" });
    expect(probe.editor.draftStatus).not.toBe("failed");
  });
});

describe("CmsApiError", () => {
  it("separates a stale path from a taken target", () => {
    const movedErr = new CmsApiError({
      status: 409, detail: "x", reason: "moved", conflictingSlug: "yeni",
    });
    const aliasErr = new CmsApiError({
      status: 409, detail: "x", reason: "alias", conflictingSlug: "yeni",
    });

    expect(movedErr.isMovedConflict).toBe(true);
    expect(movedErr.isAliasConflict).toBe(false);
    expect(aliasErr.isMovedConflict).toBe(false);
    expect(aliasErr.isAliasConflict).toBe(true);
  });

  it("separates the two rename conflicts from each other and from a race", () => {
    const taken = new CmsApiError({
      status: 409, detail: "x", reason: "taken", conflictingSlug: "bir-yeni",
    });
    const alias = new CmsApiError({
      status: 409, detail: "x", reason: "alias", conflictingSlug: "bir-yeni",
    });
    const race = new CmsApiError({ status: 409, detail: "x" });

    expect(taken.isSlugTakenConflict).toBe(true);
    expect(taken.isAliasConflict).toBe(false);
    expect(alias.isAliasConflict).toBe(true);
    expect(alias.isSlugTakenConflict).toBe(false);
    expect(alias.conflictingSlug).toBe("bir-yeni");

    expect(race.isConflict).toBe(true);
    expect(race.isSlugTakenConflict).toBe(false);
    expect(race.isAliasConflict).toBe(false);
    expect(race.conflictingSlug).toBe(null);
  });
});
