// @vitest-environment jsdom
/**
 * Creating a record in a `UserDefined` collection from the rail's create pane.
 *
 * Everything except the publish request is shared with `AutoGenerated`: the
 * same slug-less draft slot, the same form, the same validation. What differs
 * is that the editor names the slug and the record is written with
 * `PUT /cms/collections/{key}/{slug}` carrying `version: null`, which is also
 * what makes an occupied slug a 400 instead of an overwrite.
 */
import { describe, it, expect, afterEach, vi } from "vitest";
import React from "react";
import { render, screen, cleanup, fireEvent, waitFor } from "@testing-library/react";

vi.mock("next/dynamic", () => ({
  default: () => {
    const Noop = () => null;
    return Noop;
  },
}));
vi.mock("next/navigation", () => ({
  usePathname: () => "/etkinlikler",
  useRouter: () => ({ refresh: () => {} }),
}));

import { CmsProvider } from "../../core/CmsProvider.jsx";
import { CollectionProvider } from "../../collections/CollectionProvider.jsx";
import { CollectionRegionPanel } from "../../admin/CollectionRegionPanel.jsx";
import { createTranslator, resolveStrings } from "../../shared/i18n/translate.js";

const t = createTranslator(resolveStrings("en"), "en");

const BASE = "https://api.test";
const KEY = "probe-events";

const jsonRes = (body, status = 200) => new Response(JSON.stringify(body), { status });

const eventsMeta = (overrides = {}) => ({
  collectionKey: KEY,
  canCreate: true,
  slugSource: "UserDefined",
  schema: {
    fields: [
      { name: "title", label: "Başlık", type: "ShortText", required: true, readOnly: false, computed: false, options: null, itemFields: null, help: null },
    ],
  },
  ...overrides,
});

/** Every request as [method, url, body]. */
let requests;

/** @param {{ meta?: object, upsert?: () => Response }} options */
function mockFetch({ meta = eventsMeta(), upsert } = {}) {
  requests = [];
  global.fetch = vi.fn(async (input, init) => {
    const url = String(input);
    const method = init?.method ?? "GET";
    requests.push([method, url, init?.body ? JSON.parse(String(init.body)) : null]);
    if (url.includes("/cms/collections/me")) return jsonRes([meta]);
    if (method === "PUT" && new RegExp(`/cms/collections/${KEY}/[^/?]+$`).test(url)) {
      if (upsert) return upsert();
      return jsonRes({
        id: "row-1", collectionKey: KEY, slug: "bahar-senligi",
        data: { title: "Bahar şenliği" }, version: 1, canEdit: true,
      });
    }
    if (method === "POST" && url.includes(`/cms/collections/${KEY}`) && !url.includes("/drafts")) {
      return jsonRes({
        id: "row-1", collectionKey: KEY, slug: "otomatik-slug",
        data: { title: "Bahar şenliği" }, version: 1, canEdit: true,
      });
    }
    if (method !== "GET") return new Response(null, { status: 204 });
    if (url.includes(`/cms/collections/${KEY}`)) {
      return jsonRes({ items: [], total: 0, offset: 0, limit: 50, virtualItems: [] });
    }
    return jsonRes({ slug: "/etkinlikler", blocks: [] });
  });
}

function renderPanel() {
  return render(
    <CmsProvider collections={CollectionProvider} config={{ baseUrl: BASE }} isAdmin getAccessToken={async () => "tok"}>
      <CollectionRegionPanel collectionKey={KEY} scope="global" />
    </CmsProvider>,
  );
}

const createRowLabel = () => t("collections.newRecordIn", { key: KEY });
const slugInput = () => screen.queryByPlaceholderText(t("collections.slugPlaceholder"));
/** The schema's own inputs: the slug box carries the same class but is not one. */
const fieldInputs = () => Array.from(document.querySelectorAll("input.inscribed-field"))
  .filter((el) => el.placeholder !== t("collections.slugPlaceholder"));

/** Open the create pane and fill the schema's one required field. */
async function openCreate(title = "Bahar şenliği") {
  await waitFor(() => expect(screen.getByText(createRowLabel())).toBeTruthy());
  fireEvent.click(screen.getByText(createRowLabel()));
  await waitFor(() => expect(fieldInputs()).toHaveLength(1));
  fireEvent.change(fieldInputs()[0], { target: { value: title } });
}

const writesTo = (method, path) =>
  requests.filter(([m, u]) => m === method && u === `${BASE}${path}`);

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("the create affordance", () => {
  it("is offered for a UserDefined collection, with a slug field", async () => {
    mockFetch();
    renderPanel();
    await openCreate();
    expect(slugInput()).toBeTruthy();
  });

  it("is offered without a slug field when the backend derives one", async () => {
    mockFetch({ meta: eventsMeta({ slugSource: "AutoGenerated" }) });
    renderPanel();
    await openCreate();
    expect(slugInput()).toBeNull();
  });

  it("stays hidden for ClaimDerived, whose slugs arrive as derived rows", async () => {
    mockFetch({ meta: eventsMeta({ slugSource: "ClaimDerived" }) });
    renderPanel();
    // The panel is up (its search box renders) but offers no create row.
    await waitFor(() => expect(screen.getByPlaceholderText(t("collections.searchRecords"))).toBeTruthy());
    expect(screen.queryByText(createRowLabel())).toBeNull();
  });
});

describe("publishing", () => {
  it("PUTs the typed slug with no version, which is what creates the row", async () => {
    mockFetch();
    renderPanel();
    await openCreate();
    fireEvent.change(slugInput(), { target: { value: "bahar-senligi" } });
    fireEvent.click(screen.getByText(t("collections.create")));

    await waitFor(() => expect(writesTo("PUT", `/cms/collections/${KEY}/bahar-senligi`)).toHaveLength(1));
    const [, , body] = writesTo("PUT", `/cms/collections/${KEY}/bahar-senligi`)[0];
    expect(body).toEqual({ data: { title: "Bahar şenliği" }, version: null });
    // The AutoGenerated route is not taken as well.
    expect(requests.some(([m, u]) => m === "POST" && u === `${BASE}/cms/collections/${KEY}`)).toBe(false);
  });

  it("trims the slug rather than addressing a row with a stray space", async () => {
    mockFetch();
    renderPanel();
    await openCreate();
    fireEvent.change(slugInput(), { target: { value: "  bahar-senligi  " } });
    fireEvent.click(screen.getByText(t("collections.create")));

    await waitFor(() => expect(writesTo("PUT", `/cms/collections/${KEY}/bahar-senligi`)).toHaveLength(1));
  });

  it("refuses an empty slug before spending a request", async () => {
    mockFetch();
    renderPanel();
    await openCreate();
    fireEvent.click(screen.getByText(t("collections.create")));

    expect(await screen.findByText(t("collections.slugMissing"))).toBeTruthy();
    expect(requests.some(([m]) => m === "PUT")).toBe(false);
  });

  it("reads the version-required 400 as an occupied slug", async () => {
    // What the upsert answers when it finds a row where the create said there
    // was none. Nothing was overwritten.
    mockFetch({
      upsert: () => jsonRes(
        { title: "Validation Failed", status: 400, detail: "Version is required when writing to existing item" },
        400,
      ),
    });
    renderPanel();
    await openCreate();
    fireEvent.change(slugInput(), { target: { value: "bahar-senligi" } });
    fireEvent.click(screen.getByText(t("collections.create")));

    expect(await screen.findByText(t("collections.slugTaken"))).toBeTruthy();
  });

  it("still POSTs when the backend owns the slug", async () => {
    mockFetch({ meta: eventsMeta({ slugSource: "AutoGenerated" }) });
    renderPanel();
    await openCreate();
    fireEvent.click(screen.getByText(t("collections.create")));

    await waitFor(() => expect(writesTo("POST", `/cms/collections/${KEY}`)).toHaveLength(1));
  });
});
